---
title: "The Rt. Rev. George Moberly"
---

## The Rt. Rev. George Moberly

**Dates:** (1803-6 July 1885)

### Description

Bishop of Salisbury

### Biography

He married (22 December 1834) Mary Anne Crokat (1812-1890).  He was headmaster of Winchester College 1835-66;  in 1866 he became Rector of Brighstone, Isle of Wight, then in 1868 Canon of Chester.  He was consecrated bishop of Salisbury 28 Oct 1869. [ODNB; <i>Dulce Domum</i>]

### Letters

- Letter from December 8, 1896.
- Letter from June 22  [1894?]
- Letter from [1886]
- Letter from [September 1885?][[footnote:2]]
- Letter from March 28th [1884] 
- Letter from March 20th 1876
- Letter from Febry 12th [1874]
- Letter from 
- Letter from April 10, 1872
- Letter from April 8, 1872
- Letter from [check 1872]
- Letter from May 20th [1871?[[footnote:1]]]
- Letter from February 16th, 1871.
- Letter from Oct 4th [1870s?] [[footnote:1]]
- Letter from September [1870]
- Letter from Jan 31st  [1870]
- Letter from Decr 13th [1869]
- Letter from Novr 6 th [1869]
- Letter from October 8, 1869.
- Letter from August 12. [1869]

*... and 24 more letters*

---

[← Back to all letters](../letters.html)
