---
title: "Charlotte Anne Elizabeth Moberly"
---

## Charlotte Anne Elizabeth Moberly

**Dates:** (16 Sept 1846-7 May 1937)

### Description

seventh daughter of the Rt. Rev. George Moberly

### Biography

Always known as Annie, she became first principal of St. Hugh’s College, Oxford. She left £3155, probate to Elspeth Milford widow and Dora Caroline Martin spinsters [LG 1975 Moberly;  will; ODNB]

### Letters

- Letter from Aug 24 [1900?]
- Letter from Sept 19 [1899]
- Letter from Sept 12  [1899?]
- Letter from Sept 7th [1899]
- [To Christabel Rose Coleridge, Aug 25 [1899]](../letters/3420_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge,  [15 August 1899]   ](../letters/3418_To_Christabel_Rose_Coleridge.html)
- [To Elizabeth Harcourt Mitchell, July 31, 1899.](../letters/3414_To_Elizabeth_Harcourt_Mitchell.html)
- [To Christabel Rose Coleridge, July 23d [1899]](../letters/3412_To_Christabel_Rose_Coleridge.html)
- Letter from [<i>c</i>. 1898][[footnote:1]]
- Letter from Sept 17th [1897]
- Letter from [May 1894]
- Letter from April 30 [1894]
- Letter from April 12, 1894.
- Letter from [dated by Coleridge after 1893]
- Letter from  [October 1888]
- Letter from [25 February 1881]
- Letter from June 1855.
- Letter from June 1854.
- Letter from [November or December 1851[[footnote:1]]]
- Letter from Sept 24th [1846[[footnote:1]]]

*... and 1 more letters*

---

[← Back to all letters](../letters.html)
