---
title: "Jane Montgomery Moore"
---

## Jane Montgomery Moore

**Dates:** (1826/7-1919)

**Maiden name:** (Colborne), the Hon. Mrs

### Description

cousin of CMY

### Biography

Daughter of the 1st Lord Seaton, she married (1857) General Sir Alexander George Montgomery Moore (1833-17 January 1919).  He was created KCB in 1900. They were childless and administration of both estates was granted  to Percy Frederick Higham Hodge:  he left £22,796, she £6083 [WWW; PB 1914; wills index]

### Letters

- Letter from April 14th 1900
- Letter from April 11 [1900]
- Letter from March 30th [1900]
- [To Mary Yonge, Oct 18th [1897[[footnote:1]]]](../letters/3385_To_Mary_Yonge.html)
- Letter from May 13th [1897]
- Letter from May 3d [1897]
- Letter from Aug 11th [1891]
- Letter from Novr 12th [after 1885]
- Letter from Sept 28th 1885
- Letter from March 28th [1884] 
- Letter from July 2d 1879
- Letter from [May 1876]
- Letter from March 20th 1876
- Letter from Novr 6th 1874
- Letter from 5 February [1874]
- Letter from Jan 8th [or perhaps 6th, 1870]
- Letter from Decr 13th [1869]
- Letter from May 1 1868
- Letter from Decr 19th [after 1863]
- Letter from July 30th [1863]

*... and 10 more letters*

---

[← Back to all letters](../letters.html)
