---
title: "The Rev. John Frewen Moor jr."
---

## The Rev. John Frewen Moor jr.

**Dates:** (1823-1906)

### Description

Vicar of Ampfield

### Biography

He was perpetual curate of Ampfield from 12 January 1853, and later Vicar of Ampfield. The only son of the Rev. John Frewen Moor, sr. (1798-1879), of Bradfield, and his first wife Mary Stevens (d. 1823), he married Frances Dorothy Grimston (1825/6-1913)  [<i>Alumni Oxonienses</i>; 1861 census]

### Letters

- [To the Reverend John Frewen Moor, May 5 [1899]](../letters/3401_To_the_Reverend_John_Frewen_Moor.html)
- [To Frederick Orridge Macmillan or Alexander Macmillan Jr, June 30th 1898](../letters/3377_To_Frederick_Orridge_Macmillan_or_Alexander_Macmillan_Jr.html)
- Letter from April 17 [1896]
- Letter from April 13th 1896
- Letter from April 29th 1893   
- Letter from June 8th [1887]
- Letter from April 15 [1887]
- Letter from April 19th [mid 1880s?]
- Letter from April 5th 1880
- Letter from April 5th 1880
- Letter from July 20th [1873?]
- Letter from July 17th [1873]
- Letter from Novr 4th [1869?]
- Letter from May 29th [1869]
- Letter from [1869]
- Letter from Oct 26th 1868
- Letter from June 12th [1867]
- Letter from Jan 3d [1867]
- Letter from Innocents’ day [28 December 1866]
- Letter from Novr 23d [1864]

*... and 5 more letters*

---

[← Back to all letters](../letters.html)
