---
title: "Mary Moore"
---

## Mary Moore

**Dates:** (b.<i>c.</i>1785)

**Maiden name:** (Kingsman)

### Description

cousin of FMY

### Biography

The Mr and Mrs Moore mentioned in these early letters are perhaps the same as Mrs More who gave warm shawls to Otterbourne schoolchildren in December 1844;  Mrs Moore sent a parcel 24 Sept 1846 including Mr Kingsman\'s chain.  All these references have therefore been rather boldly associated with Mary Kingsman, a niece of FMY\'s mother Mary (Kingsman) Bargus, daughter of her brother William George Kingsman (b.1755).  The younger Mary Kingsman married (Otterbourne 1823) Stephen Roger Moore. In 1848 she proved the will of her uncle John Kingsman (1764-1848) who left legacies to her, FMY, JBY, CMY and the Rev. Thomas Westcombe. She can probably be identified with the Maria Kingsman mentioned in the CMY\'s autobiographical chapters (Coleridge, <i>Life</i>, 7), the orphan niece who was a member of the Bargus household during FMY\'s childhood.  Details of the descendants of CMY\'s great-grandfather the Rev. Thomas Kingsman (1717-1779), Vicar of Botley, are at http://freepages.genealogy.rootsweb.ancestry.com/~kingsman/kingsman/england/indiI13063.html

### Letters

- Letter from Oct 22d [1851[[footnote:1]]]
- Letter from Sept 24th [1846[[footnote:1]]]
- Letter from April 19th  [1845[[footnote:1]]]
- Letter from Otterbourn [5 January 1845[[footnote:1]]]
- Letter from Decr 13th [1844]
- Letter from 25 September 1838

---

[← Back to all letters](../letters.html)
