---
title: "Elizabeth Barnett"
---

## Elizabeth Barnett

**Dates:** (28 Nov 1810-15 April 1900)

### Description

sister-in-law of the Very Rev. William John Butler

### Biography

Second cousin of the Very Rev. William Butler, who was married to her younger sister Emma Barnett, she supported his good works at Wantage.  She lived with her father George Henry Barnett (d. 1871) and younger sister Louisa at Glympton and in Wilton Crescent. [H. Barnett, <i>Glympton</i>;  LG 1952 Barnett formerly of Glympton] 

### Letters

- [To Mary Caroline Butler, April 11th 1899](../letters/3403_To_Mary_Caroline_Butler.html)
- Letter from December 12, 1896
- Letter from January 17, 1894
- Letter from August 21, 1893.
- Letter from 7 June 1892
- Letter from January 10 1890
- Letter from [December 1889]
- Letter from Easter Eve [?31 March 1888]
- Letter from November 19, 1887
- Letter from St. Michael [29 September 1887]
- Letter from [January 1887][[footnote:1]]
- Letter from November 12. [1886]
- Letter from April 2 [1886]
- Letter from February 27 [1886]] 
- Letter from September 22, 1878
- Letter from July 9th [before 1877[[footnote:1]]]
- Letter from [check 1872]
- Letter from June 18th [1869]
- Letter from June 14th [1869]
- Letter from [1865?] 

*... and 20 more letters*

---

[← Back to all letters](../letters.html)
