---
title: "John William Parker jr."
---

## John William Parker jr.

**Dates:** (1820-9 Nov 1860)

### Description

publisher

### Biography

In partnership with his father, John William Parker, sr., he published CMY’s early bestsellers of the 1850s such as <i>The Heir of Redclyffe</i>. The firm should not be confused with that of John Henry Parker of Oxford, who published <i>Kenneth</i>. [DLB 106]

### Letters

- [To Sir Walter Besant, Febry 7th [1899?][[footnote:1]]](../letters/3394_To_Sir_Walter_Besant.html)
- Letter from Novr 24th 1862
- Letter from March 26th 1861
- Letter from Novr 22nd 1860
- Letter from Novr 20th [1860]
- Letter from July 31st 1860
- Letter from July 5th 1860
- Letter from July 3d 1860
- Letter from June 5th 1860
- Letter from March 16th 1860
- Letter from March 8th 1860
- Letter from Jany 13th 1860
- Letter from Decr 8th 1859
- Letter from Novr 1st 1859
- Letter from Oct 29th 1859
- Letter from October 4th 1859
- Letter from June 24th 1859
- Letter from April 12th [1859]
- Letter from April 9th 1859
- Letter from April 2d 1859

*... and 13 more letters*

---

[← Back to all letters](../letters.html)
