---
title: "Frances Sophia Coleridge Patteson"
---

## Frances Sophia Coleridge Patteson

**Dates:** (1825/6-27 April 1913)

### Description

sister of the Rt. Rev. J. C. Patteson

### Biography

She was daughter of Sir John Patteson by his second marriage to Frances Coleridge, and thus related to CMY. She died at 74 Via della Croce, Rome, and probate was granted to Arthur John Coleridge Mackarness; she left £16,044 [census, will]

### Letters

- Letter from June 6th [1900]
- [To Mary Yonge, April 14th [?1899]](../letters/3404_To_Mary_Yonge.html)
- [To Christabel Rose Coleridge, Decr 9th  [1898]](../letters/3388_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge, Oct 19 [1898]](../letters/3386_To_Christabel_Rose_Coleridge.html)
- Letter from Easter Eve [4 April 1896]
- Letter from Aug 9th [1889?]
- Letter from St. Michael [29 September 1887]
- Letter from March 31st  [1887?]
- Letter from June 25th 1885
- Letter from April 9th 1885[[footnote:1]]
- Letter from [late June or early July] 1884. 
- Letter from April 29th [1884-91?][[footnote:1]]
- Letter from Decr 8th [1883]
- Letter from Novr 9th 1881
- Letter from  Novr 9th 1872
- Letter from June 6th [1872?]
- Letter from April 22nd [1872]
- Letter from December 8 [1871]
- Letter from Christmas Day [25 December], 1867.
- Letter from November 4, 1867

*... and 11 more letters*

---

[← Back to all letters](../letters.html)
