---
title: "The Rt. Rev. John Coleridge Patteson"
---

## The Rt. Rev. John Coleridge Patteson

**Dates:** (1827-20 Sept 1871)

### Description

missionary Bishop of Melanesia

### Biography

He was killed in the Santa Cruz or Queen Charlotte Islands, the outer part of the New Hebrides, now administratively part of the Solomon Islands  [ILN 9 Dec 1871 559 text 561 picture;  Oxford Hammond Atlas of the World; Sir John Gutch <i>Martyr of the Islands</i> (1971); ODNB]

### Letters

- Letter from [<i>c</i>.  1900]
- Letter from [late June or early July] 1884. 
- Letter from March 3d 1876
- Letter from Oct 24th [1875][[footnote:1]]
- Letter from April 24th 1875
- Letter from March 26th [1874]
- Letter from March 15th [1874]
- Letter from Decr 2nd [1872]
- Letter from June 17th 1872
- Letter from 14 May 1872
- Letter from April 25th 1872
- Letter from April 23, 1872.
- Letter from March 23d 1872
- Letter from [early January 1872]
- Letter from Jany 17th 1872
- Letter from January 10, 1872.
- Letter from Jan. 1, 1872.
- Letter from Jan 1st [1872]
- Letter from Innocents\' Day [28 December 1871]
- Letter from December 8 [1871]

*... and 29 more letters*

---

[← Back to all letters](../letters.html)
