---
title: "Catherine Barter"
---

## Catherine Barter

**Dates:** (b.1818/9)

### Description

traveller and schoolmistress

### Biography

The daughter of the Rev. Charles Barter, Rector of Sarsden, and niece of the Rev. Robert Speckott Barter, she seems to have lived near her brother the Rev. Henry Barter, Vicar of Shipton-under-Wychwood, and run (in 1871) a small school, whose pupils included a South African ward named Salome Melango. CMY calls her ‘Kate Barter’ and refers to her ‘young Zulus’.  She is not to be confused with her sister-in-law Elspeth Catherine ‘Kitty’ (Moberly) Barter, or with her first cousin Katherine Mary (Barter) Wordsworth.  She was the author of an anonymous travel book <i>Alone among the Zulus: The narrative of a journey through the Zulu country, South Africa. By a plain woman</i> (London: SPCK 1866) and has an entry in S. O. Spencer, <i>British settlers in Natal, 1824-1857: A Biographical Register</i> (2001). She was born at Broadstone, Oxfordshire.

### Letters

- Letter from Nov 21st 1877 
- Letter from Sept 26th [1868-9?]
- Letter from May 21st 1860
- Letter from [November or December 1851[[footnote:1]]]
- Letter from Sept 24th [1846[[footnote:1]]]

---

[← Back to all letters](../letters.html)
