---
title: "Frances Mary Peard"
---

## Frances Mary Peard

**Dates:** (1835-1923)

### Description

member of the Gosling Society,  novelist, contributor to <i>MP</i> (1866-85) and to the <i>Monthly Paper of Sunday Teaching</i>

### Biography

She was a Gosling as ‘Fernseed’ from about 1865.  She was the daughter of Captain Peard, RN, and lived at Sparnow, Torquay.  She was  sister of Charlotte (Peard) Kekewich. [Harris, <i>F. M. Peard</i>]

### Letters

- [To Christabel Rose Coleridge, Aug 25 [1899]](../letters/3420_To_Christabel_Rose_Coleridge.html)
- Letter from Aug 21 [1899]
- [To Christabel Rose Coleridge,  [15 August 1899]   ](../letters/3418_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge, Aug 12 [1899]](../letters/3416_To_Christabel_Rose_Coleridge.html)
- Letter from Decr 27th 1889
- Letter from Decr 20th 1882
- Letter from June 6 th [1882]
- Letter from Sept 8th [?1880-1888]
- Letter from March 29th [1880]
- Letter from [24 February 1877] 
- Letter from March 20th 1876
- Letter from Aug 1st [1873]
- Letter from July 23, 1873
- Letter from July 2nd 1873
- Letter from Sept 9th [1871]
- Letter from [1871?]
- Letter from [1869/70?]
- Letter from Aug 28th [1869]
- Letter from August 10. [1869]
- Letter from July 12th [1869?]

*... and 24 more letters*

---

[← Back to all letters](../letters.html)
