---
title: "Elizabeth P. Roberts"
---

## Elizabeth P. Roberts

### Description

contributor to <i>MP</i> (1852-9)

### Biography

The author of the ‘Garland for the Year’, who preserved the letters which shed such a useful light on the early history of <i>MP</i>, signed her contributions E. P. R. or Elizabeth P. Roberts.  She may perhaps be identified with Elizabeth Piddocke Roberts (b. Kingswinford, Staffs. 1821) who published a book of verse in 1845. That person was the daughter of John Piddocke Roberts (b.1794/5) and his wife Susannah Maria Morris (b. 1789/90), who had been married at Kingswinford in 1819;  he is described in the 1841 census of Armitage, Staffs. as a land agent, and in the 1851 Isle of Man census as a landed proprietor.  By 1861 Elizabeth and her widowed mother were staying in West Bromwich, and she is described as a governess.  Since the \'Garland\' author\'s father evidently died in 1859 it is likely they are one and the same.

According to the IGI records  she was one of at least ten children, of whom several died young.  Survivors included Rebecca Surgy Roberts (b. 1831) who acted as a companion to a cousin in the Isle of Wight (1851, 1861 census), Phoebe Cordelia Roberts (1828-after 1881) and Martha Sarah Roberts (1835-1909) who married (1852) Thomas Oxenbould, a banker’s clerk.  

Roberts’s ‘Garland for the Year’ may possibly be the ‘semi botanical papers’ of which CMY wrote ‘I used to repent  - of admitting them’. 

[1841 census, Armitage with Handsacre, Staffs.;  parents Isle of Man 1851 census; 1861 census with cousin Lydia Morris, chemist, at West Bromwich;  Oxenboulds, 1871, 1891 census, Handsworth;  BMD indexes; IGI]

### Letters

- Letter from Novr 5th 1860 
- Letter from Nov 3d 1860
- Letter from St John’s day [27 December] 1859                    
- Letter from Febry 16th 1858   
- Letter from Novr 13th 1857
- Letter from June 13th 1857
- Letter from Febry 16th [1855]
- Letter from Decr 7th [1854]
- Letter from Novr 4th [1854]
- Letter from June 5th [1854]
- Letter from March 11th [1854]
- Letter from Jany 16th [1854]
- Letter from Decr 31st [1853]
- Letter from Novr 29th [1853]
- Letter from July 9th [1853]
- Letter from Whitsuneve [14 May 1853]
- Letter from March 17th [1853]
- Letter from Novr 22d [1852]
- Letter from Nov 8th [1852]
- Letter from Oct 19th [1852]

*... and 20 more letters*

---

[← Back to all letters](../letters.html)
