---
title: "Margaret Eliza Roberts"
---

## Margaret Eliza Roberts

**Dates:** (1833-1919 Montreux)

### Description

author of <i>Mademoiselle Mori</i>

### Biography

She was educated by her stepfather, the Rev. Henry Latham (1794-1866 ODNB);  she was a contributor to <i>MP</i> (1864-92).  Her most successful work was  <i>Mademoiselle Mori:  A Tale of Modern Rome</i> (1860), which CMY encouraged Parker to print;  she published as ‘the author of <i>Mademoiselle</i> Mori’.  CMY had a  plan to co-author German history with her; she suffered a strain of the hip in 1873; and lived in Torquay.  She has titles in the <i>British Library Catalogue</i> 1857-1901.  A letter in the Bodleian from Roberts to Bullock calls Grace Latham her cousin, and perhaps there was a blood relationship with some of the Lathams. (ODNB; Blain, <i>Feminist Companion</i>;  Mary Harris, <i>Frances Mary Peard</i> says she died at Territet]

### Letters

- Letter from Febry 15th [1901]
- Letter from Sept 1 [1899?]
- [To Sir Walter Besant, Febry 7th [1899?][[footnote:1]]](../letters/3394_To_Sir_Walter_Besant.html)
- Letter from Sept 10th 1892
- Letter from November 12. [1886]
- Letter from Sept  3d [1881]
- Letter from Sept 8th [?1880-1888]
- Letter from Jany 31st 1877
- Letter from Oct 30th 1874
- Letter from Aug 1st [1873]
- Letter from Sept 11th 1872
- Letter from Aug 31st [1872]
- Letter from May 11 [1872]
- Letter from July 18th 1871
- Letter from May 20th [1871?[[footnote:1]]]
- Letter from June 1st 1868
- Letter from Aug 12 [1867]
- Letter from May 11th [1866]
- Letter from March 15th [1866]
- Letter from Feb 17th [1866]    

*... and 8 more letters*

---

[← Back to all letters](../letters.html)
