---
title: "The Rt. Rev. George Augustus Selwyn"
---

## The Rt. Rev. George Augustus Selwyn

**Dates:** (1809-11 Apr 1878)

### Description

Bishop of New Zealand and subsequently of Lichfield

### Biography

He married (1839) Sarah Harriet Richardson (d. 25 Mar 1907).  He was educated at Eton and St John’s College, Cambridge (BA 1831);  he became Bishop of New Zealand in  1841 and Bishop of Lichfield in 1868.

### Letters

- Letter from Aug 11th 1893
- Letter from March 15th [1874]
- Letter from June 17th 1872
- Letter from April 25th 1872
- Letter from April 22nd [1872]
- Letter from March 23d 1872
- Letter from [early January 1872]
- Letter from Jany 17th 1872
- Letter from January 10, 1872.
- Letter from Jan. 1, 1872.
- Letter from December 30 [1871]
- Letter from Innocents\' Day [28 December 1871]
- Letter from December 21, 1868.
- Letter from October 3, 1868.
- Letter from November 4, 1867
- Letter from [August 1865]
- Letter from [‘Southern Cross’ between Auckland and Norfolk Island, May 1864]
- Letter from April 27, 1864.
- Letter from [November 1862]
- Letter from July 13th 1860

*... and 8 more letters*

---

[← Back to all letters](../letters.html)
