---
title: "The Rt. Rev. John Richardson Selwyn"
---

## The Rt. Rev. John Richardson Selwyn

**Dates:** (1844-12 Feb 1898)

### Description

son of the Rt. Rev. George Augustus Selwyn

### Biography

He was educated at St John's College Auckland, Eton, Trinity College Cambridge (BA 1866). He was ordained in 1869 and married, first (1872), Clara Innes.  He succeeded Patteson as Bishop of Melanesia (1877).  He married, secondly (1885), Annie Catherine Mort, retired and became Master of Selwyn Coll Cambridge [DNZB, ODNB] His biography makes it clear he was in England June 1889-January 1890, and then returned for good to Europe in September 1891;  this is obscured in ODNB.

### Letters

- [To the Countess of Glasgow, Sept 25th 1898](../letters/3381_To_the_Countess_of_Glasgow.html)
- Letter from November 3, [1893[[footnote:1]]]
- Letter from Aug 11th 1893
- Letter from Aug 18th [1889?]
- Letter from Aug 9th [1889?]
- Letter from June 25th 1885
- Letter from June 25th 1885
- Letter from April 9th 1885[[footnote:1]]
- Letter from November 4, 1867
- Letter from March 28th [1857]
- Letter from June 9, 1854

---

[← Back to all letters](../letters.html)
