---
title: "Anne Sturges Bourne"
---

## Anne Sturges Bourne

**Dates:** (1809-9 Dec 1891)

### Description

landowner

### Biography

Daughter of William Sturges Bourne (1769-1845), she was a rich philanthropic spinster.  A lifelong friend of [[person:464]Mary Anne Dyson], they shared interests in educational and charitable work. Their very copious correspondence, with much detail on Tractarian projects and much gossip, survives in Hampshire Record Office.  Together they encouraged the young CMY’s philanthropic and literary work.  Anne Sturges Bourne appears to have been the author of the review of <i>My Life and What Shall I Do With It</i>? which appeared in 1861.   [Her death aged 92 was reported in the <i>Daily News</i> 15 Dec 1891]

### Letters

- [To Penelope Anne Laura Packe, April 18th 1899](../letters/3405_To_Penelope_Anne_Laura_Packe.html)
- Letter from Midsummer Day [21 June 1897]
- Letter from Mar 5th 1896
- Letter from Decr 14th 1891
- Letter from Sept 5th 1888
- Letter from June 22d [1888]
- Letter from St. Michael [29 September 1887]
- Letter from September 22, 1878
- Letter from Sept 13th 1876
- Letter from Aug 17th [1876]
- Letter from May 20th [1871?[[footnote:1]]]
- Letter from Feb 20th [1871]
- Letter from Sept 2nd [1869]
- Letter from August 22nd [1864]
- Letter from May 23d 1861
- Letter from Febry 23d 1861
- Letter from Febry 19th 1861
- Letter from 16th Febry 1861
- Letter from May 21st 1860
- Letter from May 16th 1860

*... and 4 more letters*

---

[← Back to all letters](../letters.html)
