---
title: "Gertrude Walter"
---

## Gertrude Walter

**Dates:** (Shotapoor 24 May 1849-20 May 1897)

### Description

housemate of CMY, sister-in-law of JBY

### Biography

Daughter of Edward Walter and Mary Emma Coulthard.  Her sister Frances married (1858) CMY\'s only brother Julian Bargus Yonge.  She moved into Elderfield with CMY in about 1872.  Her illness began 8 years before 1871.
 [Bombay Baptisms N/3/24/118; \'she would have been 48 on the 24th\']   

CMY described her movingly in ‘Our Tender Ones’ <i>Mothers in Council</i> 9 (January 1899) 20-27, 26:

‘Let me draw the picture of a real invalid not long passed away.  She was a bright active girl of fourteen when rheumatic fever set in, followed by arthritis.  Gradually, during nearly twenty years, every power was taken from her;  first one knee was affected, then the other, then she could no longer sit at the piano, she moved on crutches, and drove in a donkey chaise;  but in time, always after severe illness and pain, these pleasures failed her, she could only be carried from one room to another or to church on a couch.  She lost her voice, and next the use of her right arm, and for several years was entirely confined to bed.’

### Letters

- Letter from Jany 28th 1898
- Letter from November 19, 1897.
- Letter from Saturday  [22 May 1897]
- Letter from May 20, 1897.
- Letter from May 20th 1897
- Letter from May 13th [1897]
- Letter from May 3d [1897]
- Letter from Feb 20th [1897]
- Letter from Febry 8th 1897
- Letter from Novr 24 [1896 or earlier]
- Letter from Novr 22 [1896][[footnote:1]]
- Letter from December 14 1895
- Letter from July 28th [1893?]
- Letter from Decr 22d [1892?]
- Letter from 7 June 1892
- Letter from October 10, 1891[[footnote:1]]
- Letter from June 7th 1890
- Letter from Decr 27th 1889
- Letter from [December 1889]
- Letter from Sept 17 [1889?]

*... and 63 more letters*

---

[← Back to all letters](../letters.html)
