---
title: "The Rev.Canon William Parsons Warburton"
---

## The Rev.Canon William Parsons Warburton

**Dates:** (1824/5-1913)

### Description

school inspector

### Biography

He was educated at Balliol College, Oxford, and was a Fellow of All Souls 1849-53.  He served as HM Inspector of Schools 1851-81, and of training schools 1881-5.  He was an honorary Canon of Winchester 1878-81, and was made a Canon in 1885.  He had three daughters Mary A. (b.1859/60), Katharine (b. 1861/2), and Charlotte (b. 1864/5) [<i>Rugby School Register, Alumni Oxonienses</i>]

### Letters

- [To Helena Mary Heathcote, July 25, 1899](../letters/3413_To_Helena_Mary_Heathcote.html)
- Letter from Decr 21st 1897
- Letter from Aug 17th 1893
- Letter from March 4th 1892
- Letter from [1890s?]
- Letter from March 4th [1889?]
- Letter from Novr 5th 1888
- Letter from 25th February [1881]
- Letter from Feb 24th [?1881[[footnote:1]]]
- Letter from Oct 15 1880
- Letter from Nov 12th [1879 or later?][[footnote:1]]
- Letter from July 4th  [1879 or later]
- Letter from April 20th 1875
- Letter from [Before June 1865]

---

[← Back to all letters](../letters.html)
