---
title: "Susanna Warren"
---

## Susanna Warren

**Dates:** (b. Edmonton 1814/5)

### Description

author of fiction and non-fiction as ‘S.W.’

### Biography

In the 1851 census she was living with her elder sister Selina Warren (b. 1812/3) at Hazlewood Farm, Hennock, near Bovey Tracey, Devon; she was staying with nephew William Henderson, woollen manufacturer, at 3 South Bailey Durham at the time of the 1861 census;  in the 1871 census she was again at Hazlewood, Hennock, with her eldest sister Charlotte Warren (b.1787/8).  It seems possible that in the 1860s she worked for the Rev. John Hawksley in Clifton as a governess.  She was author of fiction and non-fiction (tracts?) from 1860, under the initials S.W., for the SPCK.

### Letters

- Letter from [1 October 1870]
- Letter from March 22nd [1870?[[footnote:2]]]
- Letter from Novr 9th [1868]
- Letter from [13 November 1865]
- Letter from Oct 7th 1864 [?]
- Letter from Aug 6th [1862]
- Letter from May 9th 1861
- Letter from Feb 7th 1861
- Letter from Nov 3d 1860

---

[← Back to all letters](../letters.html)
