---
title: "Florence Wilford"
---

## Florence Wilford

**Dates:** (Woolwich 29 Feb 1836-?1897)

### Description

novelist, contributor to <i>MP</i> (1866-83), member of the Gosling Society

### Biography

Daughter of Major-General Edmund Neal Wilford (1800-1881), RA, Governor of the Royal Military Academy, Woolwich, until his retirement, she was a Gosling as ‘Turkscap’ from June 1865; her address then was c/o Mrs Chrystall\'s,. St. Cross, Winchester. In the 1851 census, she was 15 and was staying at Bromley Kent, in the company of Maria Cristall, whom CMY describes as her aunt.  In 1881 she and her elder sister Emma, 48, were living with their father in St. Leonards; in 1891 she and Emma were staying in Bournemouth.  Her Royal Literary Fund file indicates that she had suffered from mental illness intermittently since 1883 and was in a private asylum in 1889 when CMY wrote a letter to them on her behalf.  (Her application was refused on the grounds ‘authorship insufficient’, which seems rather harsh since she had published sixteen books since 1858.)  CMY assured Bullock (16 March 1895) that she was well and at home with her sister.  She was probably the Florence Wilford who died at Keynsham, Glos. in 1897. [IGI; RLF application 2311, born at Woolwich]

### Letters

- Letter from March 16 [1895]
- Letter from Oct 18th 1890
- Letter from October 10, 1890.
- Letter from June 19th 1889
- Letter from April 30th 1889
- Letter from January 27 [1886]
- Letter from Decr 1st [or 14?] [1883]
- Letter from Decr 20th 1882
- Letter from July 2, 1881.
- Letter from Feb 26th 1880
- Letter from October 1, 1878
- Letter from April 4 th [1876?]
- Letter from July 23, 1873
- Letter from July 2nd 1873
- Letter from Innocents day [28 December 1872]
- Letter from Sept 9th [1871]
- Letter from Aug 11th [1871]
- Letter from Feb 20th [1871]
- Letter from September 20, 1869.
- Letter from January 19, 1869

*... and 21 more letters*

---

[← Back to all letters](../letters.html)
