---
title: "Maria Wilson"
---

## Maria Wilson

**Dates:** (1820/1-7 Dec 1908)

**Maiden name:** (Trench)

### Description

wife of the Rev. Robert Francis Wilson

### Biography

She married (6 May 1847) the Rev. Robert Francis Wilson, Vicar of Rownhams (d. 1888).  The <i>Court and Lady’s Magazine</i> (April 1847) 57 has ‘Trench, Maria, d. of the rev. Frederick S. Trench and lady Helen Trench, of Kilmorony, to the rev. Francis Wilson, son of Thomas Wilson esq. formerly M. P. for the city of London;  at the parish church of Athy, by the rev. John Keble, vicar of Hursley Hants, May 6 [1847]’ She was 1st cousin of T.R.F. Cooke Trench and, through her mother, of Sir William Heathcote\'s children by his first marriage. Frances Dorothy (Grimston) Moor was her first cousin, daughter of her aunt Jane Trench.  [PB 1914 Ashtown; <i>Erminois</i>]

### Letters

- Letter from March 24th 1874
- Letter from December 30 [1871]
- Letter from July 18th 1871
- Letter from February 11, 1869.
- Letter from [November 1868]
- Letter from April 6, 1866
- Letter from Aug 18 1863. 
- Letter from Jany 10th 1861 
- Letter from Novr 7th 1857
- Letter from Decr 14th [1853]

---

[← Back to all letters](../letters.html)
