---
title: "The Rev. Robert Francis Wilson"
---

## The Rev. Robert Francis Wilson

**Dates:** (1808/9-8 Oct 1888)

### Description

Vicar of Rownhams

### Biography

He married (6 May 1847) Maria Trench (1820/1-7 Dec 1908).  He was educated at Oriel College, Oxford, and served as curate of Hursley, then curate of Ampfield from April 1841;  he resigned Ampfield in October 1853;  he was perpetual curate of Baldersby Yorks 1858-63, and vicar of Rownhams 1863; he left issue [PB 1914 Ashtown; <i>Clergy List</i>]

### Letters

- Letter from December 12, 1896
- Letter from  [October 1888]
- Letter from Feb 28 th 1879
- Letter from Ash Wednesday [6 March] 1878
- Letter from Feb 26[or8?] 1878
- Letter from Decr 29th 1877 
- Letter from March 24th 1874
- Letter from December 30 [1871]
- Letter from August 6. [1869]
- Letter from Jany 25th [1869]
- Letter from St. S[imon]. & J[ude]. [28 October] 1868
- Letter from October 8, 1868
- Letter from October 5, 1868
- Letter from November 4, 1867
- Letter from July 12th 1862
- Letter from Novr 25th 1861
- Letter from [September 1861]
- Letter from Sept 24th [1846[[footnote:1]]]

---

[← Back to all letters](../letters.html)
