---
title: "The Rev. William Harris Walter Bigg Wither"
---

## The Rev. William Harris Walter Bigg Wither

**Dates:** (1809-1899)

### Description

curate of Otterbourne to 1871 and subsequently Rector of Hardwick, Bucks.

### Biography

His father Harris Bigg Wither had proposed to Jane Austen. [R. F. Bigg-Wither, <i>Materials for a History of the Wither Family</i> Winchester, Warren 1907]

### Letters

- [To the Reverend John Frewen Moor, May 5 [1899]](../letters/3401_To_the_Reverend_John_Frewen_Moor.html)
- [To Marianne Bigg Wither, March 17 [1899]](../letters/3399_To_Marianne_Bigg_Wither.html)
- [To Marianne Bigg Wither, August, 11[[footnote:1]] 1898.](../letters/3380_To_Marianne_Bigg_Wither.html)
- Letter from May 13th [1897]
- Letter from Novr 22 [1896][[footnote:1]]
- Letter from March 24th [1896?][[footnote:1]]
- Letter from [dated by Coleridge after 1893]
- Letter from Easter [5 April 1885]
- Letter from March 26th 1882
- Letter from Jan 21st 1881 [for 1882][[footnote:1]]
- Letter from July 20th 1881
- Letter from July 23, 1873
- Letter from July 17th [1873]
- Letter from April 30th [1873]
- Letter from April 21st 1872 [1873?]
- Letter from 14 May 1872
- Letter from December 30 [1871]
- Letter from S Philip & S James [1 May] 1871
- Letter from [1871?]
- Letter from Oct 4th [1870s?] [[footnote:1]]

*... and 39 more letters*

---

[← Back to all letters](../letters.html)
