---
title: "Elizabeth Wordsworth"
---

## Elizabeth Wordsworth

**Dates:** (23 June 1840-30 Nov 1932)

### Description

contributor to <i>MP</i> (1871-1893), principal of Lady Margaret Hall

### Biography

Daughter of the Rt. Rev. Christopher Wordsworth, she was appointed Lady Principal of Lady Margaret Hall in 1878.  She contributed a poem to <i>MP</i> in 1871 under the name \'VERITAS\' and probably was the author of another 16 poems which appeared under that pseudonym to February 1883.  

 [Battiscombe, <i>Reluctant Pioneer</i>]

### Letters

- [To Elizabeth Harcourt Mitchell, July 31, 1899.](../letters/3414_To_Elizabeth_Harcourt_Mitchell.html)
- Letter from January 2, 1897
- Letter from March 28th [1884] 
- Letter from 25th August [1882]
- Letter from Sept 17 th [1881]
- Letter from July 17th 1879
- Letter from March 14th 1879
- Letter from 24 November 1877 
- Letter from Novr 16th 1877 
- Letter from 12 November 1877 
- Letter from Novr 26th 1874
- Letter from Oct 30th 1874
- Letter from 5 February [1874]
- Letter from 14 May 1872
- Letter from May 11 [1872]
- Letter from Aug 4th 1871 
- Letter from May 17th 1871

---

[← Back to all letters](../letters.html)
