---
title: "Charlotte Cordelia Yonge"
---

## Charlotte Cordelia Yonge

**Dates:** (1839/40- 7 Sept 1929)

**Maiden name:** (Pode)

### Description

cousin and goddaughter of CMY

### Biography

First cousin of CMY, she was daughter of WCY’s sister Anne (Yonge) Pode.  She married (26 Aug 1862) Rev. Duke Yonge (1823-1881), of Puslinch. [census, LG]

### Letters

- Letter from February 26, 1901
- Letter from May 2 [1900]
- Letter from March 27 [1900]
- Letter from Decr 12th  [1899]
- Letter from Oct 10 [1899]
- [To Mary Yonge, April 14th [?1899]](../letters/3404_To_Mary_Yonge.html)
- [To Mary Yonge, Jan 26th [1899]](../letters/3393_To_Mary_Yonge.html)
- [To Christabel Rose Coleridge, Decr 9th  [1898]](../letters/3388_To_Christabel_Rose_Coleridge.html)
- Letter from March 17th [1895]
- Letter from March 17 [1895]
- Letter from [December 1893]
- Letter from Aug 17th [1876]
- Letter from March 23d 1872
- Letter from Sept 13th [1871]
- Letter from Sept 6th [1869]
- Letter from September 5, 1869
- Letter from Sept 4th [1869]
- Letter from [Late August 1868]
- Letter from Aug 4th [1863]
- Letter from July 25th [1863]

*... and 1 more letters*

---

[← Back to all letters](../letters.html)
