---
title: "Charlotte Fortescue Yonge"
---

## Charlotte Fortescue Yonge

**Dates:** (d. 19 Jan 1940)

### Description

cousin of CMY, contributor to <i>MP</i> (1891)

### Biography

Daughter of the Rev. John Eyre Yonge, her address at death was Cotswold, Station Road, Brading Isle of Wight; probate was granted to Catherine Mildred Leser wife of Karl Frederick Leser [will]

### Letters

- Letter from February 26, 1901
- Letter from Feb 4th  [1901]
- Letter from Decr 3d [1900]
- Letter from Oct 15 th [1900?]
- Letter from Oct 5 th 1900
- Letter from Novr 24th [1899]
- [To Charlotte Fortescue Yonge, July 20, 1899](../letters/3411_To_Charlotte_Fortescue_Yonge.html)
- [To Beatrice Henrietta Heathcote, Feb 11 [1898]](../letters/3371_To_Beatrice_Henrietta_Heathcote.html)
- Letter from Decr 27th 1897
- [To Mary Yonge, Oct 18th [1897[[footnote:1]]]](../letters/3385_To_Mary_Yonge.html)
- Letter from Sept 17th [1897]
- Letter from April 12, 1894.
- Letter from July 29th [1885?[[footnote:1]]]
- Letter from Aug 28th [1880s?]
- Letter from Febry 3d [1865]

---

[← Back to all letters](../letters.html)
