---
title: "Jemima Blackburn"
---

## Jemima Blackburn

**Dates:** (1823-1909)

**Maiden name:** (Wedderburn)

### Description

artist and naturalist

### Biography

Jemima (Wedderburn) Blackburn (1823-1909), a Scottish naturalist and painter, met CMY through [[person:1252]Frederic Rogers] (1811-1889), later Lord Blachford, a Devon Tractarian who was married to her cousin Georgina Colvile (d.1900). Blackburn’s memories of CMY are printed in Robert Fairley, <i>[[otherbook:63]Jemima: Paintings and Memoirs of a Victorian Lady]</i> (Edinburgh : Canongate, 1988), 128:  ‘Charlotte Yonge was a friend of the Rogers and was asked to stay while I was visiting them. It was a very small house and we were lodged in two little garrets next one another, and used to brush out our hair together before going to bed, and so soon became friends. She was very good looking with dark hair and fine eyes, spoke pleasantly and was a little above middle height. We talked of many things. I found her not at all formidable, as one feared she might be, being so well informed; one might almost say learned.  . . . I kept up the friendship as long as she lived, and got a good many letters from her while I was illustrating her books.’   She married Hugh Blackburn, Professor of Mathematics at Edinburgh University. 

Jemima Blackburn discovered the habits of the cuckoo.

### Letters

- Letter from Novr 14th 1895
- Letter from Decr 29th [1894]
- Letter from Feb 12th 1885 
- Letter from Febry 26th 1864
- Letter from Feb 25:1864
- Letter from Febry 17th [1864]
- Letter from Febry 1st [1864]
- Letter from Jany 27th [1864]
- Letter from Jany 25th 1864
- Letter from Novr 27th 1863
- Letter from May 5th [1862]
- Letter from April 22nd 1861
- Letter from Jany 10th 1861 
- Letter from June 5th 1860
- Letter from Jan 24th [1857]
- Letter from March 17th [1856]
- Letter from Dec 1st [1854]
- Letter from Oct 10th  [1854]
- Letter from May 26th [1854]
- Letter from May 13th [1854]

*... and 2 more letters*

---

[← Back to all letters](../letters.html)
