---
title: "The Rev. Duke Yonge"
---

## The Rev. Duke Yonge

**Dates:** (21 June 1823-7 Oct 1881)

### Description

cousin of CMY

### Biography

The fourth and only surviving of the five sons of the Rev. John Yonge of Puslinch, and Alethea Henrietta (Bargus) Yonge, he inherited Puslinch in 1877 (John, James, John Bargus and Edmund Charles having predeceased him).  He was curate of Newton Ferrars in 1849, and subsequently Rector of Newton Ferrars like his father.  He married (26 Aug 1862) Charlotte Cordelia Pode (1839/40-7 Sept 1929), who was his second cousin (she was CMY's first cousin).  He shared two of her eight great-grandparents, whereas he shared four of CMY's eight great-grandparents.  According to a letter of his youngest daughter Alethea’s, he had wished to marry CMY.

### Letters

- Letter from May 3d 1888
- Letter from Sept 23 rd 1878
- Letter from Aug 17th [1876]
- Letter from Novr 8th 1875
- Letter from Sept 13th [1871]
- Letter from Novr 6 th [1869]
- Letter from September 20, 1869.
- Letter from Sept 6th [1869]
- Letter from September 5, 1869
- Letter from Sept 4th [1869]
- Letter from Novr 6th [1868]
- Letter from October 5, 1868
- Letter from Sept. 30, 1868
- Letter from [Late August 1868]
- Letter from Aug 4th [1863]
- Letter from May 12th [1862]
- Letter from September 10, 1858.
- Letter from Thursday 1st Oct [1857]
- Letter from 26 Septr 1857
- Letter from March 19th [1855]

*... and 12 more letters*

---

[← Back to all letters](../letters.html)
