---
title: "Frances Mary Yonge"
---

## Frances Mary Yonge

**Dates:** (1795-28 Sept 1868)

**Maiden name:** (Bargus)

### Description

mother of CMY

### Biography

FMY married (25 Oct 1822) William Crawley Yonge.  [Hampshire: - Marriage License allegations, Bishop of Winchester, 1689-1837 has: Yonge, William-Crawley, of Cornwood, co. Devon, gent., b., s. of Duke & Catherine Yonge, bap. 26 Jun 1795 , at C., by affidavit of John Yonge, of Puslink, co. Devon, clerk, & Frances-Mary Bargus, of Otterbourne, dau. of Thomas and Mary Bargus, b. 13 Jan , bap. 14 Jan 1793 , at St. Michael's, Winchester, at O., 23 Oct 1822.]

### Letters

- Letter from April 11 [1900]
- Letter from Novr 24th [1899]
- Letter from Sept 26th 1899
- Letter from Sept 22 1899
- Letter from Novr 6th[?1898-1900] [[footnote:1]]
- [To Christabel Rose Coleridge, Oct 19 [1898]](../letters/3386_To_Christabel_Rose_Coleridge.html)
- [To Beatrice Henrietta Heathcote, Feb 11 [1898]](../letters/3371_To_Beatrice_Henrietta_Heathcote.html)
- [To Mary Yonge, Oct 18th [1897[[footnote:1]]]](../letters/3385_To_Mary_Yonge.html)
- Letter from Sept 20th 1897  
- Letter from June 2nd 1896
- Letter from [August 1893]
- Letter from Sept 9th 1890
- Letter from January 15, 1890.
- Letter from Jany 13th 1890
- Letter from June 10th 1889
- Letter from June 23d [1886]
- Letter from July 29th [1885?[[footnote:1]]]
- Letter from Feb 12th 1885 
- Letter from Oct 22nd [1879?]
- Letter from October 1, 1878

*... and 125 more letters*

---

[← Back to all letters](../letters.html)
