---
title: "Julian Bargus Yonge"
---

## Julian Bargus Yonge

**Dates:** (31 Jan 1830-17 October 1891)

### Description

brother of CMY

### Biography

He was educated at Eton and Balliol College Oxford (BA 1853).  He joined the Rifle Brigade 1851, entered the Middle Temple 1855.  He married (9 Sept 1858) Emma Frances Walter (1839-1913).  He was a J.P. for Hampshire;  sold Otterbourne House to Major Robert Scarlett in 1891 and died ‘a few days later’ (<i>John Keble’s Parishes</i>, 149), at 70 Kensington Gardens Square in the presence of his son Maurice [death certificate] but according to the probate of his will at 2 Radnor Place Hyde Park.

### Letters

- [To Helena Mary Heathcote, May 5 1898](../letters/3370_To_Helena_Mary_Heathcote.html)
- Letter from Jan 27th  1896
- Letter from Jan 23d 1896
- Letter from October 10, 1891[[footnote:1]]
- Letter from Aug 11th [1891]
- Letter from [<i>c</i>.1890] 
- Letter from May 3d 1888
- Letter from June 1st [?1886]
- Letter from Sept 28th 1885
- Letter from July 29th [1885?[[footnote:1]]]
- Letter from April 29th [1884-91?][[footnote:1]]
- Letter from Decr 21st 1882
- Letter from Decr 9th 1882
- Letter from February 21st [1880s?]
- Letter from July 9th 1877 
- Letter from June 1st 1877 
- Letter from April 28th 1877 
- Letter from [24 February 1877] 
- Letter from July 27th 1876
- Letter from July 3d [1876]

*... and 93 more letters*

---

[← Back to all letters](../letters.html)
