---
title: "Mary Yonge"
---

## Mary Yonge

**Dates:** (1816/7-2 April 1910)

### Description

cousin of CMY

### Biography

Second daughter of the Rev. John Yonge and Alethea Henrietta Bargus, she was the last surviving of their ten children.

### Letters

- Letter from May 2 [1900]
- Letter from April 11 [1900]
- Letter from April 3d [1900]
- Letter from March 30th [1900]
- Letter from March 27 [1900]
- Letter from March 24 [1900]
- Letter from Decr 15th 1899
- Letter from Decr 12th  [1899]
- Letter from Novr 24th [1899]
- Letter from Oct 10 [1899]
- [To Mary Yonge, July 1st[1899]](../letters/3409_To_Mary_Yonge.html)
- [To Mary Yonge, June 15th 1899](../letters/3408_To_Mary_Yonge.html)
- [To Mary Yonge, April 14th [?1899]](../letters/3404_To_Mary_Yonge.html)
- [To Mary Yonge, Jan 26th [1899]](../letters/3393_To_Mary_Yonge.html)
- Letter from [1899-1900?]
- [To Christabel Rose Coleridge, Decr 9th  [1898]](../letters/3388_To_Christabel_Rose_Coleridge.html)
- [To Misey , May 28th 1898](../letters/3374_To_Misey_.html)
- [To Mary Yonge, Oct 18th [1897[[footnote:1]]]](../letters/3385_To_Mary_Yonge.html)
- Letter from Sept 17th [1897]
- Letter from July 1st [1897]

*... and 68 more letters*

---

[← Back to all letters](../letters.html)
