---
title: "Maurice Edward Yonge"
---

## Maurice Edward Yonge

**Dates:** (1867-6 Apr 1940)

### Description

nephew of CMY

### Biography

He seems to have trained as an engineer.  He married (19 Apr 1899) Maude Woods (d.1938).  He died at St Faiths, Merdon Avenue, Chandlers Ford, Eastleigh, Probate was granted at Bristol 5 June 1940 to George Hubert Woods and Henry Jex Woods  for £221 4s. He went to Stubbington House school, near Fareham, a naval preparatory school. [1881 census; will]

### Letters

- Letter from April 11 [1900]
- Letter from March 30th [1900]
- Letter from March 2 [1900]
- [To Christabel Rose Coleridge, Aug 12 [1899]](../letters/3416_To_Christabel_Rose_Coleridge.html)
- [To Mary Yonge, Jan 26th [1899]](../letters/3393_To_Mary_Yonge.html)
- Letter from  [November or December?1894]
- Letter from Feby 7th [1890]
- Letter from Easter day [5 April 1885]
- Letter from Sept  3d [1881]
- Letter from Ash Wednesday [6 March] 1878
- Letter from Aug 7 th [1876]
- Letter from [May 1876]
- Letter from May 8 th [1876]
- Letter from Sept 13th [1871]
- Letter from Jany 4th [1870]
- Letter from Decr 13th [1869]
- Letter from June 1st 1868

---

[← Back to all letters](../letters.html)
