---
title: "The Hon. Mildred Mary Adams"
---

## The Hon. Mildred Mary Adams

**Dates:** (1847-14 January 1929)

**Maiden name:** (Coleridge)

### Description

member of the Gosling Society as ‘Ladybird’

### Biography

The only daughter of John Duke Coleridge, later 1st Lord Coleridge, and Jane Fortescue Seymour (d. 1878), she married (24 June 1885) Charles Warren Adams.  She had a  row with her father about her marriage which was made public because Adams sued her brother Bernard for libel.  She was a  Gosling as Ladybird 1859- <i>c.</i> 1866;   [PB, Coleridge, <i>Story of a Devonshire House</i>; <i>The Times</i> reports of the libel trial 21, 22 November 1884, 5, 25 June 1885.]

### Letters

- Letter from October 10, 1890.
- Letter from [September 1885?][[footnote:2]]
- Letter from Easter [5 April 1885]
- Letter from Decr 8th [1883]
- Letter from Decr 1st [or 14?] [1883]
- Letter from Aug 20th 1878
- Letter from Jany 20th 1874
- Letter from Easter Eve [30 March 1872]
- Letter from Novr 6 th [1869]
- Letter from May 25 th [1867]
- Letter from Oct 30th [1865]
- Letter from [1865/6]
- Letter from Novr 22d 1864
- Letter from  Feb 21st [1862 ]
- Letter from St Stephen [26 December 1861]
- Letter from Novr 22nd [1861]
- Letter from May 23d 1861
- Letter from  Sept 27th [1851 ]

---

[← Back to all letters](../letters.html)
