---
title: "The Rev. Henry Albany Bowles jr."
---

## The Rev. Henry Albany Bowles jr.

**Dates:** (1859- 2 March 1943)

### Description

Vicar of Otterbourne and nephew-in-law of CMY

### Biography

He married (7 August 1884) (Louisa) Alethea Yonge (1863-1941).  He was ordained in 1883 and served first (1889) as curate of St Matthew, Haberham Eaves, Burnley.  He was made Rector of Arlington, near Barnstaple in 1884 and in 1892 became Vicar of Otterbourne.  He left £26,505. [Clergy List, will]

### Letters

- Letter from July 9th      [1900]
- Letter from June 15 [1900]
- Letter from May 2 [1900]
- Letter from April 23d [1900?]
- Letter from Oct 10 [1899]
- Letter from Sept 7th [1899]
- [To Charlotte Fortescue Yonge, July 20, 1899](../letters/3411_To_Charlotte_Fortescue_Yonge.html)
- [To Marianne Bigg Wither, March 17 [1899]](../letters/3399_To_Marianne_Bigg_Wither.html)
- [To Anna Meredith Barrett Lennard, Oct 7th 1898](../letters/3383_To_Anna_Meredith_Barrett_Lennard.html)
- Letter from Sept 25 [1897?]
- Letter from July 1st [1897]
- Letter from Midsummer Day [21 June 1897]
- Letter from May 20, 1897.
- Letter from May 20th 1897
- Letter from May 13th [1897]
- Letter from May 3d [1897]
- Letter from April 28, 1897.
- Letter from Feb 20th [1897]
- Letter from Febry 8th 1897
- Letter from Novr 22 [1896][[footnote:1]]

*... and 6 more letters*

---

[← Back to all letters](../letters.html)
