---
title: "Anna Rachel Bramston"
---

## Anna Rachel Bramston

**Dates:** (Witham 1848/9-1931)

### Description

contributor to <i>MP</i> (1887)

### Biography

She was the daughter of the Rev. John Bramston by his second wife, and half-sister of Mary Eliza Bramston.  In the 1891 census she was living at Witham Close, Kingsgate St., Winchester with her widowed mother Anna Bramston aged 84. She seems to have lived later with the novelist Amelie Claire Leroy, and they adopted a daughter called Juliette (perhaps a relation of Leroy’s?). The two of them published two books on the history of Winchester.  They were closely involved in the foundation of the Winchester High School (now St. Swithin’s School). She was on the Diocesan Council of the GFS in 1878, she and CMY in charge of the literature department.

### Letters

- Letter from July 17 [1900]
- [To Christabel Rose Coleridge, Aug 12 [1899]](../letters/3416_To_Christabel_Rose_Coleridge.html)
- [To Mary Yonge, July 1st[1899]](../letters/3409_To_Mary_Yonge.html)
- [To Beatrice Henrietta Heathcote, Feb 11 [1898]](../letters/3371_To_Beatrice_Henrietta_Heathcote.html)
- Letter from [<i>c</i>. 1898][[footnote:1]]
- Letter from Novr 25th [1897] [[footnote:1]]
- Letter from Aug 22 [1897]
- Letter from March 8 [1890s?]
- Letter from July 7th [1880]
- Letter from October 1, 1878
- Letter from Sept 12th 1876
- Letter from Oct 15th  [1875-8?]

---

[← Back to all letters](../letters.html)
