---
title: "Mary Eliza Bramston"
---

## Mary Eliza Bramston

**Dates:** (1841-2 February 1912)

### Description

contributor to <i>MP</i> (1870-96), novelist

### Biography

Daughter of the Rev. John Bramston by his first marriage and half-sister of Anna Bramston, she was a  prolific writer of fiction and non-fiction, generally for young women: she collaborated with CMY and others on <i>Astray</i>. She seems to have acted for some years as governess to the daughters of Archbishop Benson.  Several of her works, such as <i>Everingham Girls</i> (1886)and <i>Apples of Sodom</i> (1889), portray intense same-sex relationships. She died at Kinshot Street Cross, Winchester, and left £8253. [<i>Journal of Clarissa Trant</i>, NUC, wills index]

### Letters

- Letter from Oct 2d [1900]
- Letter from May 12 [1900]
- Letter from April 23d [1900?]
- Letter from Sept 7th [1899]
- [To Christabel Rose Coleridge, Decr 9th  [1898]](../letters/3388_To_Christabel_Rose_Coleridge.html)
- Letter from [February 1890]
- Letter from Decr 27th 1889
- Letter from [December 1889]
- Letter from Feb 8th 1888
- Letter from January 27 [1886]
- Letter from Aug 25 [1883]
- Letter from April10 th [1883]
- Letter from Decr 20th 1882
- Letter from June 5th 1879
- Letter from October 1, 1878
- Letter from Aug 15th 1877 
- Letter from Sept 12th 1876
- Letter from July 31st 1875
- Letter from May 24th 1875
- Letter from Novr 26th 1874

*... and 2 more letters*

---

[← Back to all letters](../letters.html)
