---
title: "The Rev. John Frederick Watkinson Bullock"
---

## The Rev. John Frederick Watkinson Bullock

**Dates:** (1840-1918)

### Biography

He succeeded his father and grandfather as Rector of Radwinter 1865-1916.  In 1902 he published the first three volumes of a projected six volume work called <i>Daily Lections for every Morning and Evening throughout the Year</i> (London: Rivington 1902).  Volume V of this work, described in his preface, was to have consisted of \'Lections on Anglican Worthies, arranged as additional Readings for Sunday\'.  These \'Biographies of Eminent Anglicans\' exist in MS and are catalogued under that name among the Bullock papers in the Bodleian Library, Oxford, but were never published, since no more of the <i>Daily Lections</i> ever appeared.  The biographies were contributed by various authors, including CMY, Elizabeth Rundle Charles and Florence Wilford.  [ Burke LG 1862, Venn, <i>Alumni Cantabrigienses</i>.  N.B. Venn\'s statement that there is an obituary in the <i>Guardian</i> 11 April 1918 seems to be inaccurate.]

### Letters

- [To the Reverend John Frederick Watkinson Bullock, Jan 2 1899](../letters/3392_To_the_Reverend_John_Frederick_Watkinson_Bullock.html)
- Letter from March 16 [1895]
- Letter from [4 January 1895]
- Letter from Novr 21 [1894?]
- Letter from Oct 30  [1894]
- Letter from Oct 20th [1894]
- Letter from July 10th 1894
- Letter from June 22  [1894?]
- Letter from June 16th 1894
- Letter from May 15th 1894
- Letter from May 4th 1894
- Letter from April 24th 1894
- Letter from March 19 1894
- Letter from March 7th 1894
- Letter from March 1st 1894
- Letter from Feb 24 [1894]
- Letter from Feb 19  [1894]
- Letter from Feb 15th 1894
- Letter from Feb 9th 1894
- Letter from Feb 6th [1894]

*... and 5 more letters*

---

[← Back to all letters](../letters.html)
