---
title: "Maria Edith Walker"
---

## Maria Edith Walker

**Dates:** (Middlesex 1843-1938)

### Description

correspondent of CMY

### Biography

The letters from CMY to Miss M. E. Walker were presented to West Sussex Record Office in 1975 by the latter\'s niece Bertha Yeats, who was then 91. [Information from Alison McCann, West Sussex Record Office]  Bertha Margaret F. Yeats (1883-1976) was the daughter of the Rev. George Yeats (b. Yorks. 1826/7), Vicar of Heworth, York, and Rosa Bertha Walker (1852-1900).  Mrs Yeats\'s sister, Maria Edith Walker, was therefore the recipient of the letters from CMY.   The Walker sisters were the daughters of Francis Walker (1809-1874), entomologist, and his wife and cousin Mary Elizabeth Ford (b. 1814/15), daughter of John Ford of Ellel Hall, Lancashire and Elizabeth Lawson.  Francis Walker, son of John Walker (1766-1824)  was a member of a family of rich and philanthropic brewers living at Arnos Grove, Southgate, Middlesex.  The Miss Lawrence referred to in the correspondence, grandmother of Maria Walker, who had been at school with Frances Mary Yonge, was perhaps the wife of John Walker.

### Letters

- Letter from June 15 1900
- Letter from Jan 6th 1900
- Letter from Decr 15th 1899
- Letter from Sept 26th 1899
- Letter from Sept 22 1899
- Letter from Sept 18th [1899]
- Letter from Sept 9th 1899

---

[← Back to all letters](../letters.html)
