---
title: "Anna Butler"
---

## Anna Butler

**Dates:** (b.1825/6)

### Description

sister of the Very Rev. William John Butler, contributor to <i>MP</i> (1852)

### Biography

An obscure figure but an important early contributor to <i>MP</i>, she seems to have shared the family scholarly interests, being a student of German and Danish and author of a book CMY refers to as your 'Scandinavian book'  in early 1856.   The letters in the Fairclough collection are clearly addressed to a sister of William Butler, who had two, Frances, who married in 1843 and died in 1851, and Anna (b.1825/6), who was still alive in 1892, author of <i>Likes and Dislikes: Some Passages in the Life of Emily Marsden</i> (1858) and several other works published as by ‘The author of Likes and Dislikes', viz., <i>Philip Bezant, or, Is Revenge Sweet</i>?  (1859), <i>The Brotherhood of St. John the Evangelist at Berlin</i> (1859),  <i>Chilcote Park, or, The Sisters</i> (1860) and <i>The Post Office Window, Being a Tale of the Night School</i> (1862).  The identification is confirmed by payments to Miss A. Butler in the bank account.

### Letters

- Letter from March 14th 1888
- Letter from Oct 2nd [1876 or earlier[[footnote:1]]]
- Letter from Aug. 16, 1870.
- Letter from Novr 20th [1860]
- Letter from April 16th 1860
- Letter from Decr 26th 1857
- Letter from June 15th 1857
- Letter from June 13th 1857
- Letter from Decr 15th [1856]
- Letter from Sept 29th [1856]
- Letter from July 11th [1856]
- Letter from June 23d [1856]
- Letter from May 19th [1856]
- Letter from [March-October 1856?[[footnote:1]]]
- Letter from Febry 11th [1856]
- Letter from Jany 28th [1856?]
- Letter from June 6th [1855]
- Letter from April 20th [1854]
- Letter from April 10th [1854]
- Letter from Febry 10th [1854]

*... and 1 more letters*

---

[← Back to all letters](../letters.html)
