---
title: "Arthur John Butler"
---

## Arthur John Butler

**Dates:** (21 June 1844-26 Feb 1910)

### Description

contributor to <i>MP</i>, Italian scholar, son of the Very Rev. William John Butler

### Biography

He married (6 April 1875) Mary Caroline Humphry. He was a fellow of Trinity College, Cambridge until 1870, worked in education office until 1887, became a partner in Rivington then Cassell, in 1894 became assistant commissioner on secondary education.  In 1899 joined PRO as editor of foreign state papers.  Translator. In 1898 he also became professor of Italian literature at UCL. [ODNB]

### Letters

- Letter from Feb 26th  [1901]
- [To Mary Caroline Butler, April 11th 1899](../letters/3403_To_Mary_Caroline_Butler.html)
- Letter from December 12, 1896
- Letter from June 14th 1894
- Letter from Sept 19th 1892
- Letter from Sept 10th 1892
- Letter from [1886]
- Letter from Febry 12th [1874]
- Letter from Febry 5th [1874]
- Letter from March 16th 1871
- Letter from March 30th [1870]
- Letter from March 4th [?1870] [[footnote:1]]
- Letter from Decr 7th [1869]
- Letter from Novr 13th [1869]
- Letter from July 12th [1869]
- Letter from July 5th [1869]
- Letter from June 18th [1869]
- Letter from June 14th [1869]

---

[← Back to all letters](../letters.html)
