---
title: "The Very Rev. William John Butler"
---

## The Very Rev. William John Butler

**Dates:** (10 February 1818-14 January 1894)

### Description

Vicar of Wantage and Dean of Lincoln

### Biography

He was ordained in 1841 and served as curate of Dogmersfield under Mary Anne Dyson’s brother. He served (1846-1880) as Vicar of Wantage, where he embarked on Tractarian improvements on a very large scale, including the establishment of the sisterhood of St. Mary the Virgin.  He married (1843) Emma Barnett, who was his second cousin.  She and her sister Elizabeth Barnett were close friends of CMY. In 1880 he moved to become a canon of Worcester, and in 1885 Dean of Lincoln;  he was made DD in 1886.  [ODNB; <i>Life and Letters of Dean Butler</i>]

### Letters

- Letter from Feb 6th [1894]
- Letter from January 17, 1894
- Letter from May 17th 1890
- Letter from July 11th [1889]
- Letter from [1886]
- Letter from Sept 7th 1885
- Letter from September [1870]
- Letter from Aug 18th [1870]
- Letter from Aug. 16, 1870.
- Letter from May 30th [1870] 
- Letter from August 9. [1869]
- Letter from June 7. [1869]
- Letter from St. S[imon]. & J[ude]. [28 October] 1868
- Letter from May 1866
- Letter from Oct 16th [1862]
- Letter from Midsummer Day [24 June 1850[[footnote:1]]]

---

[← Back to all letters](../letters.html)
