---
title: "Ann Maria Carter Smith"
---

## Ann Maria Carter Smith

**Dates:** (Kentish Town 1835-15 Oct 1909 Chislehurst)

### Description

contributor to <i>MP</i> (1856-90), novelist

### Biography

Daughter of the Reverend Richard Carter Smith (1802-1864) and Mary Williamson. The letters indicate that at some point Ann Carter Smith had lived in Norway and that she had a brother in the navy. [wills index, left £40,997, probate to Cecil Newton Goodhall; parish register]

### Letters

- Letter from Aug 10th [1891-1893]
- Letter from July 27th [1887]
- Letter from April 10th [1884]  
- Letter from Jan 16th 1883
- Letter from Sept 6th [1882]
- Letter from Feb 15th 1882
- Letter from July 20th 1881
- Letter from May 24th 1881
- Letter from May 23d [1881]
- Letter from May 21st [1881]
- Letter from May 16th [1881]
- Letter from March 12  [1881]
- Letter from Aug 2d 1878
- Letter from Novr 9th 1877 
- Letter from Oct 22 1877 
- Letter from Feb 13th [1869]
- Letter from Oct 8th [1868]
- Letter from [July 1868[[footnote:1]]] 
- Letter from Jany 23d [1868]
- Letter from [1868]

*... and 72 more letters*

---

[← Back to all letters](../letters.html)
