---
title: "Alethea Anderson Morshead"
---

## Alethea Anderson Morshead

**Dates:** (28 March 1815-22 July 1863)

**Maiden name:** (Yonge)

### Description

cousin of CMY

### Biography

The eldest daughter of the Rev. John Yonge of Puslinch and Alethea Henrietta Bargus, she married (1845) John Philip Anderson Morshead of Widey Court, her second cousin, whose paternal grandmother was Elizabeth Yonge of Puslinch.  They had six sons. She and her younger sister Anne were known as ‘great A and little a’, after a nursery rhyme.  [LG 1871 Morshead]

### Letters

- Letter from Sept 4th [1869]
- Letter from Aug 4th [1863]
- Letter from July 30th [1863]
- Letter from July 27th [1863]
- Letter from July 25th [1863]
- Letter from July 13th [31 July 1863][[footnote:2]]
- Letter from Thursday 1st Oct [1857]
- Letter from Friday [23 March 1855]
- Letter from Friday [17 March 1854]
- Letter from Oct 22d [1851[[footnote:1]]]
- Letter from Oct 13th [1851[[footnote:1]]]
- Letter from Friday 30th Oct? [sic] [1846]
- Letter from Sept 19th  [1846[[footnote:1]]]
- Letter from Otterbourn [5 January 1845[[footnote:1]]]
- Letter from Novr 19th [1844]
- Letter from Oct 21st 1844[[footnote:1]]
- Letter from Sept 30th 1844
- Letter from Wednesday 5 [December 1838]
- Letter from 25 September 1838
- Letter from August 6, 1838

---

[← Back to all letters](../letters.html)
