---
title: "Anne Elizabeth Mary Anderson Morshead"
---

## Anne Elizabeth Mary Anderson Morshead

**Dates:** (1845/6-1928)

### Description

missionary and schoolmistress

### Biography

Always called Mary, she was the daughter of Pentire Anderson Morshead and Charlotte Story; her paternal grandmother was a Yonge which made her a cousin of CMY.  She joined the Gosling Society as ‘Bog Oak’ and was one of the liveliest contributors to <i>The Barnacle</i>, she left when she went to South Africa to do missionary and social work in 1868; she later wrote a history of the <i>Universities Mission to Central Africa 1859-1896</i> (1897) and  <i>A Pioneer and Founder . . . Robert Gray, first Bishop of Cape Town</i> (1905).  She  also edited <i>Eikon Basilike</i> (1887). For many years, from at least 1881, she was a matron at Marlborough St Giles Industrial School for Girls, Andover. Many of her contributions to <i>MP</i> are signed ‘Bog Oak’.  <i>Jackson’s Oxford Journal</i> (30 May 1891) reports her speaking at a GFS conference as a member of the committee for the Winchester Diocese. She was first cousin to fellow-Goslings Mary Sunderland and Anne Baker.

### Letters

- Letter from Febry 15th [1901]
- Letter from Feb 4th  [1901]
- Letter from Jan 29th [1901]
- Letter from Oct 15 th [1900?]
- Letter from Oct 2d [1900]
- Letter from Aug 24 [1900?]
- Letter from Aug 1 [1900]
- Letter from July 30th [1900]
- Letter from July 17 [1900]
- Letter from Feb 12th 1900
- Letter from Jan 20th [1900]
- Letter from Novr 24th [1899]
- Letter from Aug 21 [1899]
- Letter from April 30 [1894]
- Letter from Jan 31 [1894]   
- Letter from November 3, [1893[[footnote:1]]]
- Letter from June 24th [after 1890[[footnote:1]]]
- Letter from March 17th 1888
- Letter from March 28th [1884] 
- Letter from Decr 20th 1882

*... and 12 more letters*

---

[← Back to all letters](../letters.html)
