---
title: "Alice Mary Coleridge"
---

## Alice Mary Coleridge

**Dates:** (1846-1907)

### Description

member of the Gosling Society, cousin of CMY

### Biography

Much the youngest daughter of Francis Coleridge (1794-1854); her mother sank into depression after her birth and she was brought up by her elder sister Harriet Duke (Coleridge) Lowe (b.1829/30), wife of the Rev. Edward Clarke Lowe (1823-1912) one of the moving spirits in the Woodard Schools movement for the education of the middle classes.  She lived with them at The College, Hurstpierpoint, and was a Gosling as ‘Gurgoyle’ 1863-after 1869.  She became Lady Warden of St. Anne's Abbot's Bromley, a Woodard girls' school, <i>c</i>. 1874 and spent the rest of her life there.  Her brother Arthur Duke Coleridge was father of Mary E. Coleridge, the poet.  She was CMY's goddaughter.  It looks from the <i>Barnacle</i> as if she spent some time living with Mildred and/or Mary Coleridge.  [ODNB; Rice, <i>Story of St. Mary's Abbot's Bromley</i>; Coleridge, <i>Story of a Devonshire House</i>]

### Letters

- Letter from Aug 9th [1889?]
- Letter from Jany 28th  [1870]
- Letter from July 30th [1867]
- Letter from July 6th [1867]
- Letter from May 25 th [1867]
- Letter from evening September 1st [1866?]
- Letter from Oct 30th [1865]
- Letter from July 25th 1865
- Letter from [1865/6]
- Letter from Novr 22d 1864
- Letter from March 24th 1862 

---

[← Back to all letters](../letters.html)
