---
title: "Christabel Rose Coleridge"
---

## Christabel Rose Coleridge

**Dates:** (1843-14 Nov 1921)

### Description

biographer of CMY

### Biography

Daughter of the Rev. Derwent Coleridge (1800-1883), headmaster (1826-41) of Helston Grammar School, Principal (1841-64) of St Mark\'s College, Chelsea, and Rector (1864-80) of Hanwell, Middlesex, and his wife Mary Simpson Pridham;  she was granddaughter of S. T. Coleridge.  The longest-serving member of the Gosling Society, she was called Chelsea Delf to 1863 and Chelsea China thereafter;  she acted as secretary and many members seem to have been recruited by her;  she was first cousin to Cobweb and Hedgerose; Ladybird, Gurgoyle, Pena and Cricket were more distant relations.  The move to Hanwell took place in August 1864. In 1873 she was evidently helping her brother Ernest run a school in his house at Chiddingfold.    Contributor to (including Debatable Ground) and later editor of <i>MP</i>.  From 1890 she was editor of <i>Friendly Leaves</i> (Jan 1876 to June 1917) a magazine, originally edited by Anne Mercier,  produced by the Girls\' Friendly Society (founded 1875). Will proved £4615 [Hainton, <i>Unknown Coleridge</i>;  DNB; will]

### Letters

- Letter from Feb 26th  [1901]
- Letter from February 26, 1901
- Letter from Febry 15th [1901]
- Letter from Feb 4th  [1901]
- Letter from Jan 29th [1901]
- Letter from Decr 3d [1900]
- Letter from Oct 15 th [1900?]
- Letter from Oct 5 th 1900
- Letter from Oct 2d [1900]
- Letter from Aug 24 [1900?]
- Letter from Aug 1 [1900]
- Letter from July 30th [1900]
- Letter from July 17 [1900]
- Letter from June 15 [1900]
- Letter from June 6th [1900]
- Letter from May 14 [1900]
- Letter from May 12 [1900]
- Letter from May 2 [1900]
- Letter from April 23d [1900?]
- Letter from April 4th 1900[[footnote:1]]

*... and 143 more letters*

---

[← Back to all letters](../letters.html)
