---
title: "Sir John Duke Coleridge, 1st Lord Coleridge"
---

## Sir John Duke Coleridge, 1st Lord Coleridge

**Dates:** (3 Dec 1820-14 June 1894)

### Description

Lord Chief Justice, contributor to <i>MP</i> (1878)

### Biography

He married first (11 Aug 1846), Jane Fortescue Seymour (1824/5-1878); and, secondly (1885) Amy Augusta Jackson Lawford (1853-1933), who had previously passed for some years as the wife of her cousin John Davies, but whose Gretna Green marriage had been declared void in 1878.  He was knighted in December 1868 on becoming solicitor general; he was created (1874) Lord Coleridge on being made chief justice of the common pleas; he became Lord Chief Justice in 1880.  [ODNB]

### Letters

- Letter from Sept 12  [1899?]
- Letter from Sept 17 th 1894
- Letter from Decr 8th [1883]
- Letter from Decr 1st [or 14?] [1883]
- Letter from June 16th 1880
- Letter from June 24th [1879]
- Letter from March 10th 1879
- Letter from Aug 20th 1878
- Letter from July 3d [1876]
- Letter from April 23, 1872.
- Letter from Easter Eve [30 March 1872]
- Letter from Decr 7th [1869]
- Letter from Oct 27th [1865]
- Letter from May 31st 1864
- Letter from April 27 1864
- Letter from May 23d 1861
- Letter from March 7th [1854]
- Letter from March 1st [1854]
- Letter from [late 1853?]
- Letter from Saturday [18 May 1850[[footnote:1]]] 

*... and 2 more letters*

---

[← Back to all letters](../letters.html)
