---
title: "Mary Frances Keble Coleridge"
---

## Mary Frances Keble Coleridge

**Dates:** (1824-25 March 1898)

### Description

daughter of Sir [[person:344]John Taylor Coleridge], cousin and lifelong friend of CMY, member of the Gosling Society

### Biography

The intimacy between CMY and Mary Coleridge is not well documented  because the letters to her were, Christabel Coleridge states, burnt in an accident, but she is very frequently referred to in letters to others.  Her 1845 engagement to Roundell Palmer, later 1st Earl of Selborne, was broken off, and she never married.  She was devoted to her niece Mildred, daughter of Lord Coleridge, and encouraged CMY to found the Gosling Society partly in order to find an outlet for Mildred\'s intellectual interests. Her Gosling name was The Old Secretary, but when Mildred lost interest in the society, she did likewise.  She was devastated by the furore over Mildred\'s 1885 marriage to Charles Warren Adams, who had sued Bernard Coleridge for libel.  In the same year her brother Lord Coleridge had married Amy Lawford, who had previously lived as the wife of her first cousin, but had then had their Gretna Green marriage declared invalid.  It appears that Mary Coleridge, like CMY, consequently disapproved of the second Lady Coleridge, and deplored her influence on her husband. [PB: Coleridge, <i>Story of a Devonshire House</i>]

A portrait of her and her sister Alethea as girls sold in 2006 is illustrated at www.artnet.com/Artists/LotDetailPage.aspx?lot_id=5830456F7F89012700A33CFAA5D

### Letters

- Letter from Feb 26th  [1901]
- Letter from Sept 12  [1899?]
- Letter from March 24th [1896?][[footnote:1]]
- Letter from [December 1889]
- Letter from Aug 9th [1889?]
- Letter from May 3d 1888
- Letter from Easter Eve [?31 March 1888]
- Letter from [September 1885?][[footnote:2]]
- Letter from Easter [5 April 1885]
- Letter from Decr 8th [1883]
- Letter from Decr 1st [or 14?] [1883]
- Letter from May 20th 1882
- Letter from Aug 28th [1880s?]
- Letter from March 14th 1879
- Letter from March 10th 1879
- Letter from Feb 28 th 1879
- Letter from July 9th 1877 
- Letter from Feb 17 th [1877] 
- Letter from July 3d [1876]
- Letter from June 1st 1876

*... and 34 more letters*

---

[← Back to all letters](../letters.html)
