---
title: "Elizabeth Charlotte Curteis"
---

## Elizabeth Charlotte Curteis

**Dates:** (b.1845)

### Description

contributor to <i>MP</i>

### Biography

This person was author, as Bessie C. Curteis, of <i>In the Marsh</i> (SPCK 1876).  East Sussex Record Office MS AMS6128/3/27 is a letter (June 1875) from Bessie Charlotte Curteis to her father Edward Barrett Curteis of Leasam House, Rye, Sussex, stating that she has been offered £50 for the manuscript of her article in the <i>Monthly Packet</i>.  She was no doubt the \'B.C.C.\' who wrote \'On Dialect\' <i>MP</i> (February 1874) 171-184.  

It therefore seems reasonable to assume that she is the \'Miss Curteis\' of Leasams to whom CMY was writing about \'your eagle and goose story\', in a letter probably dating from 1872.

Her mother Frances Curteis (1816/7-1887) might have been the Mrs Curteis to whom CMY addressed a letter of 1878, but Elizabeth  A. Curteis seems more plausible

### Letters

- Letter from July 10th [1872?]

---

[← Back to all letters](../letters.html)
