---
title: "The Rev. Edmund Doidge Anderson Morshead"
---

## The Rev. Edmund Doidge Anderson Morshead

**Dates:** (1849-1912)

### Description

cousin of CMY, schoolmaster

### Biography

Third son of Rev. John Philip Anderson Morshead and Alethea Yonge, he was a brilliant child and educated at Winchester and New College, Oxford 1867-72.  He got a  double first and returned to serve as assistant master at Winchester College 1872-1904.  He married (1 Aug 1878) Mary, fourth sister of William Andrewes Fearon, headmaster of Winchester College 1884-91.  He died of General Paralysis of the Insane after having spent some months in Holloway Sanatorium [Winchester College Register;  Wainewright, <i>Winchester College</i>; ODNB; LG 1871 Morshead; Hants RO MS 67M922W/82/21]

### Letters

- Letter from April 3d [1900]
- [To Mary Yonge, June 15th 1899](../letters/3408_To_Mary_Yonge.html)
- Letter from Feb 16th [1898]
- [To Beatrice Henrietta Heathcote, Feb 11 [1898]](../letters/3371_To_Beatrice_Henrietta_Heathcote.html)
- Letter from Jan 29th [1898?]
- Letter from July 28th [1893?]
- Letter from June 24th [after 1890[[footnote:1]]]
- Letter from July 27th 1876
- Letter from June 1st 1876
- Letter from October 5, 1868
- Letter from Aug 4th [1863]
- Letter from Oct 22d [1851[[footnote:1]]]

---

[← Back to all letters](../letters.html)
