---
title: "Mary Anne Dyson"
---

## Mary Anne Dyson

**Dates:** (28 March 1809-29 Sept 1878)

### Description

writer and schoolmistress

### Biography

Life-long friend of CMY, she lived with her much older half-brother, the Rev. Charles Dyson, Rector of Dogmersfield, until his death in 1860, and latterly at Church Crookham.  Her will was proved by her nephew the Rev Francis Dyson, estate under £10,000. She was an invalid ‘confined her to a sofa and latterly even to her bed’ ; author of <i>Conversations with Cousin Rachel, Little Alice and her Sister, The White Kitten, Out in the Dark, Ivo and Verena</i>, [wills index, obit <i>MP</i> (1878, 2, 521-5]

### Letters

- [To Penelope Anne Laura Packe, April 18th 1899](../letters/3405_To_Penelope_Anne_Laura_Packe.html)
- Letter from December 8, 1896.
- Letter from  [August 1893]
- Letter from January 10 1890
- Letter from February 27 [1886]] 
- Letter from Oct 3d [1878]
- Letter from October 1, 1878
- Letter from September 22, 1878
- Letter from Aug 17th [1876]
- Letter from April 6, 1875
- Letter from May 7, 1874.
- Letter from [August 1873][[footnote:1]]
- Letter from May 11 [1872]
- Letter from April 10, 1872
- Letter from April 8, 1872
- Letter from March 23d 1872
- Letter from December 30 [1871]
- Letter from March 3d 1871
- Letter from Jany 4th [1870]
- Letter from December 16 [1869]

*... and 55 more letters*

---

[← Back to all letters](../letters.html)
