---
title: "Marion Finlaison"
---

## Marion Finlaison

**Dates:** (b. London 1834/5-1914)

### Description

schoolmistress, subeditor of <i>MP</i>

### Biography

CMY\'s neighbour Marion Finlaison (1834/5-1914) is described in Coleridge, <i>[[otherbook:40]Life]</i>, 272, 280. She ran a small boarding-school in Otterbourne and acted as sub-editor of <i>MP</i>. Although Marion is what she wrote on the census forms, it appears she was actually baptised Catherine Jane.  She was the daughter of William Finlaison (1789-1852), Captain RN (he was brother of the actuary and was on the <i>Beagle</i>, briefly also governor of Ascension I) and Mary Anne Ovenden.  In 1861, calling herself Marion C. C [or J?]. Finlaison,  she was living with her mother in the household of her sister Mary Isobell (1819-1900)  and brother-in-law, the Rev. [[person:758]Henry Jenner] (1820-1898), Rector of Preston, Kent.  Jenner  was later made Bishop of Dunedin New Zealand (though rejected as too High) and Bishop of the Eglise Catholique Gallicane. Marion Finlaison acted as subeditor of the <i>MP</i> and  ran a small boarding school in Otterbourne from late 1870s, probably successor of the school run by Mary Adams.  She was evidently known by her family as Kate.  She lived at Wingham between Preston and Otterbourne.  [Not in PO Directory 1875, listed in White\'s Directory 1878; Finlaison letters; geocities.]

### Letters

- Letter from Feb 26th  [1901]
- Letter from Febry 15th [1901]
- Letter from Oct 2d [1900]
- Letter from Aug 24 [1900?]
- Letter from Aug 14 1900
- Letter from July 30th [1900]
- Letter from July 17 [1900]
- Letter from July 9th      [1900]
- Letter from March 24 [1900]
- Letter from Feb 3 1900
- Letter from Sept 19 [1899]
- [To Charlotte Fortescue Yonge, July 20, 1899](../letters/3411_To_Charlotte_Fortescue_Yonge.html)
- [To Mary Yonge, April 14th [?1899]](../letters/3404_To_Mary_Yonge.html)
- [To Christabel Rose Coleridge, Oct 19 [1898]](../letters/3386_To_Christabel_Rose_Coleridge.html)
- Letter from Jany 28th 1898
- [To Mary Yonge, Oct 18th [1897[[footnote:1]]]](../letters/3385_To_Mary_Yonge.html)
- Letter from Feb 20th [1897]
- Letter from April 29th 1893   
- Letter from April 27 [1892[[footnote:1]]].
- Letter from July 20th 1891

*... and 12 more letters*

---

[← Back to all letters](../letters.html)
