---
title: "Margaret Gatty"
---

## Margaret Gatty

**Dates:** (1809-1873)

**Maiden name:** (Scott)

### Description

children’s writer and naturalist

### Biography

She married (8 July 1839) the Rev. Alfred Gatty (1813-1903), Vicar of Ecclesfield; she was the mother of Juliana Horatia (Gatty) Ewing, and a contributor to <i>MP</i> (1857-69).   Gatty’s <i>Aunt Judy’s Tales</i> (1859) and <i>Aunt Judy’s Letters</i> (1862) were made up of contributions to the <i>MP</i> from 1858 to 1865. \'Aunt Judy\' was there represented as an older sister telling stories to her younger brothers and sisters, and was based on Gatty’s daughter [[person:494]Juliana Horatia Gatty] (1841-1885), later Ewing, who herself began to contribute to the <i>MP</i> in 1861. In 1866 Gatty began to edit a periodical for George Bell called <i>[[other:54]Aunt Judy’s Magazine]</i> and most of the later fiction of both mother and daughter appeared there.

### Letters

- Letter from Friday [November or December 1870][[footnote:1]]
- Letter from Febry 4 [1869[[footnote:2]]]
- Letter from Feb 17th [1868]
- Letter from Novr 20th [1867]
- Letter from Feb 16th [1867?]
- Letter from [“early” 1866] [[footnote:1]]
- Letter from March 25th 1865
- Letter from March 24. 1865
- Letter from Jany 17th 1865
- Letter from [1865]
- Letter from Decr 12th [1864]
- Letter from Decr 2nd [1862]
- Letter from Aug 8th [1862]
- Letter from [September 1861]
- Letter from [1861]
- Letter from Nov 3d 1860

---

[← Back to all letters](../letters.html)
