---
title: "Louisa Halliday"
---

## Louisa Halliday

**Dates:** (Hyderabad 11 Dec 1840-1916)

**Maiden name:** (Walter)

### Description

sister of Gertrude Walter and Frances (Walter) Yonge

### Biography

Daughter of Lt- Col Edward Walter, she married (1866) Francis Edward Halliday (1834-1911).  She was sister of Gertrude Walter, Frances Yonge and Mary (Walter) Woollcombe.  She had a large family of whom CMY most often mentions her daughter Georgina Frances (Halliday) Mansfield (b.1868/9) who was three in 1871. [India Office, Bombay Baptisms, 1871 census when they were staying at Medstead with cousins]

### Letters

- Letter from Feb 4th  [1901]
- Letter from July 9th      [1900]
- Letter from Oct 10 [1899]
- Letter from May 3d 1888
- Letter from April 19th [mid 1880s?]
- Letter from Easter Eve [30 March 1872]
- Letter from Jany 4th [1870]
- Letter from Novr 6 th [1869]
- Letter from June 1st 1868
- Letter from April 24th [1868?[[footnote:1]]]
- Letter from [August 1866[[footnote:1]]]
- Letter from April 6, 1866
- Letter from September 10, 1858.

---

[← Back to all letters](../letters.html)
