---
title: "Sophia Jane Harrison"
---

## Sophia Jane Harrison

**Dates:** (1826-1891)

**Maiden name:** (Collinson)

### Description

wife of Thomas Elliot Harrison

### Biography

Daughter of the Rev. John Collinson, Rector of Boldon, and Amelia King,  she married (6 January 1859), as his second wife, Thomas Elliot Harrison (1808-1888), of Whitburn, Sunderland-on-Wear, the distinguished railway engineer and entrepreneur, see ODNB.  They had two sons and four daughters;  one of the latter, Katharine Charlotte Harrison, was CMY’s goddaughter.  CMY stayed with them at Whitburn and at their house in Paddington in London.  See the dedication of <i>Grisly Grisell</i>.  Sophia Harrison’s sister Thomasine Septima Collinson married the Rev. Henry de Winton (d. 1895), Archdeacon of Brecknock, and is probably the Mrs de Winton mentioned in the letter to her.  However,  Julia Cecilia Collinson (1812-1876) who married first (1831) Walter de Winton, ne Wilkins (d.1840), and secondly (1857) William Stretton (d 1868) , whose biography CMY wrote in <i>Women Novelists of Queen Victoria’s Reign</i>, was also a member of this family, another sister of Mrs Harrison.  [Sutherland, <i>Longman Companion</i>, under Stretton; LG 1952 de Winton; ODNB T. E. Harrison; PB 1914;  Coleridge, <i>Life</i> 31-2; corr. N&Q (1908)]

### Letters

- Letter from June 1st [?1886]
- Letter from May 2nd 1876
- Letter from Novr 6th [1868]
- Letter from June 18th [1866]

---

[← Back to all letters](../letters.html)
