---
title: "Selina Heathcote"
---

## Selina Heathcote

**Dates:** (1814/5-1901)

**Maiden name:** (Shirley), Lady

### Description

second wife of Sir William Heathcote

### Biography

She married Sir William Heathcote 5th Bt. as his second wife (18 May 1841).

### Letters

- [To Frederick Orridge Macmillan, July 12th 1898](../letters/3379_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan or Alexander Macmillan Jr, June 30th 1898](../letters/3377_To_Frederick_Orridge_Macmillan_or_Alexander_Macmillan_Jr.html)
- [To Frederick Orridge Macmillan, June 28th1898](../letters/3376_To_Frederick_Orridge_Macmillan.html)
- Letter from Jan 29th [1898?]
- Letter from Aug 5th 1897
- Letter from Jan 10th 1893
- Letter from Novr 4th [1886]
- Letter from Aug 21st [1881]
- Letter from Easter Eve [31 March], 1866.
- Letter from February 16, 1859
- Letter from April 21 1857
- Letter from December 1 [1854]
- Letter from February 25, 1854.
- Letter from February 23, 1853
- Letter from Oct 21st 1844[[footnote:1]]

---

[← Back to all letters](../letters.html)
