---
title: "Sir William Heathcote 5th Bt."
---

## Sir William Heathcote 5th Bt.

**Dates:** (17 May 1801-17 Aug 1881)

### Description

landowner

### Biography

He married, first (8 Nov 1825) the Hon. Caroline Frances Perceval (d. 3 Mar 1835) and secondly (18 May 1841) Selina Shirley (d. 1901).

### Letters

- [To Helena Mary Heathcote, July 25, 1899](../letters/3413_To_Helena_Mary_Heathcote.html)
- [To Frederick Orridge Macmillan or Alexander Macmillan Jr, June 30th 1898](../letters/3377_To_Frederick_Orridge_Macmillan_or_Alexander_Macmillan_Jr.html)
- [To Frederick Orridge Macmillan, June 28th1898](../letters/3376_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, June 23rd 1898](../letters/3375_To_Frederick_Orridge_Macmillan.html)
- Letter from Novr 30th 1897
- Letter from April 9th [late 1890s?]
- Letter from January 10 1890
- Letter from Oct 29th 1887
- Letter from Sept 17 th [1881]
- Letter from Aug 21st [1881]
- Letter from August 19, 1881
- Letter from Decr 29th 1877 
- Letter from Aug 7 th [1876]
- Letter from July 27th 1876
- Letter from June 1st 1876
- Letter from April 23, 1872.
- Letter from April 10, 1872
- Letter from April 8, 1872
- Letter from Jan 30th 1872
- Letter from Jany 17th 1872

*... and 29 more letters*

---

[← Back to all letters](../letters.html)
