---
title: "Arthur Donald Innes"
---

## Arthur Donald Innes

**Dates:** (Simla 1863/4-1938)

### Description

editor and publisher

### Biography

He graduated from Oriel College Oxford in 1887, was publisher of <i>MP</i> and of some of CMY’s books, contributor (1892-8), took over from CMY as coeditor of <i>MP</i> in 1894. After the collapse of his publishing business, he seems to have worked for Cassell’s and later lectured in Indian history at SOAS.  He came from a family of Indian administrators and civil servants.  [WWW]

### Letters

- Letter from Feb 26th  [1901]
- Letter from Oct 9th 1900
- Letter from Oct 5 th 1900
- Letter from Aug 24 [1900?]
- Letter from Sept 19 [1899]
- Letter from Sept 12  [1899?]
- Letter from Sept 7th [1899]
- Letter from Aug 29 [1899]
- [To Christabel Rose Coleridge, Aug 25 [1899]](../letters/3420_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge, Aug 12 [1899]](../letters/3416_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge, July 23d [1899]](../letters/3412_To_Christabel_Rose_Coleridge.html)
- [To Charlotte Fortescue Yonge, July 20, 1899](../letters/3411_To_Charlotte_Fortescue_Yonge.html)
- [To Mary Yonge, July 1st[1899]](../letters/3409_To_Mary_Yonge.html)
- [To Frederick Orridge Macmillan, 1899](../letters/3391_To_Frederick_Orridge_Macmillan.html)
- Letter from March 30 [1897]
- Letter from Oct 16th 1895
- Letter from November 3, [1893[[footnote:1]]]
- Letter from 
- Letter from April 21st [1893]
- Letter from February 27 [1893]

*... and 36 more letters*

---

[← Back to all letters](../letters.html)
