---
title: "The Rt. Rev. Henry Lascelles Jenner"
---

## The Rt. Rev. Henry Lascelles Jenner

**Dates:** (1820-1898)

### Description

Bishop of Dunedin, Vicar of Preston

### Biography

His appointment to the bishopric of Dunedin, New Zealand, was abortive, but he was active there 1866-71.  Later he was Bishop of the Eglise Catholique Gallicane 1882-93.  His address was Preston Vicarage, Dover.  He married Mary Isabel, eldest daughter of Capt Finlaison RN, sister of Marion Finlaison, sub-editor of <i>MP</i>. He was a contributor to <i>MP</i> (1884), and perhaps also the Bishop contributing to <i>MP</i>  in 1878 as \'H. L. J.\'  He was son of Sir Herbert Jenner-Fust, the judge in  the Gorham case.  It seems probable that he was ‘Vertumnus I’, whose address was Preston Vicarage, Sandwich, who conducted the ‘Monthly Packet Botanical Society’ between June 1879 and November 1882, and who subsequently took part in the Spider competitions as ‘Vertumnus I’. [WWW]

### Letters

- Letter from June 16th 1894
- Letter from June 9th [1888]
- Letter from Sept 7th 1885
- Letter from Feb 21st  1880

---

[← Back to all letters](../letters.html)
