---
title: "Ellen Julia Johns"
---

## Ellen Julia Johns

**Dates:** (Bath 1821-1895 Winchester)

**Maiden name:** (Field)

### Description

wife of the Rev. Charles Alexander Johns

### Biography

She married (Chelsea 1843) the Rev. Charles Alexander Johns, naturalist and schoolmaster.  She seems to have been related to the Keary sisters, possibly  through their mother, daughter of Hall Plumer of Bilston Hall, brother of Sir Thomas Hall Plumer. [1881 census; information from Melissa Hardie;  census]

### Letters

- Letter from July 27th 1878
- Letter from Novr 10th 1877 
- Letter from Febry 1st 1875
- Letter from July 2nd 1873
- Letter from March 23d 1872
- Letter from [1872? 1873?]
- Letter from Novr 8th  [1871]
- Letter from May 11th 1871
- Letter from March 31 [1870?] 
- Letter from [1870-2?][[footnote:1]]
- Letter from Dec 10th [1869[[footnote:2]]]
- Letter from Sept 27th [1869]
- Letter from Oct 8th [1868]
- Letter from Novr 30th [1867?]
- Letter from July 9th [1867]
- Letter from Decr 22d [1865]	
- Letter from July 25th 1865
- Letter from March 10th 1865
- Letter from Febry 14 [1865]
- Letter from Febry 3d [1865]

*... and 2 more letters*

---

[← Back to all letters](../letters.html)
