---
title: "Anna Maria Keary"
---

## Anna Maria Keary

**Dates:** (3 March 1825-March 1879)

### Description

writer,  contributor to <i>MP</i> (1865-76)

### Biography

Sixth child of the Rev. William Keary, Rector of Bilton, perpetual curate of Sailcoates, and rector of Nunnington. Her mother was daughter of Hall Plumer of Bilston Hall, brother of Sir Thomas Hall Plumer. She and her sister Eliza went to live in Addison Road 1854, later in Bedford Gardens.  She worked in a children\'s hospital and was rather deaf. They seem to have been related to the Johns family. IIn 1873 she seems to have taken part in the essay-writing part of the Gosling Society, but if she had a sobriquet it is not known.  [Eliza Keary <i>Memoir of Annie Keary</i>;Vital records index for death]

### Letters

- Letter from Feb 26th 1877 
- Letter from Febry 1st 1875
- Letter from July 2nd 1873
- Letter from Oct 12th [1871?]
- Letter from Sept 9th [1871]
- Letter from July 30th [1867]
- Letter from July 9th [1867]
- Letter from May 19th [1866]
- Letter from April 26th [1866]
- Letter from Febry 5th [1866]
- Letter from March 24. 1865
- Letter from Febry 10th 1865
- Letter from Feb 8 1865
- Letter from Febry 7th 1865
- Letter from Oct 31st 1864
- Letter from Oct 19th [1864]

---

[← Back to all letters](../letters.html)
