---
title: "The Rev. John Keble"
---

## The Rev. John Keble

**Dates:** (1792-29 March 1866)

### Description

Vicar of Hursley

### Biography

He was ordained in 1816;  he married (10 Oct 1835) Charlotte Clarke;  he was buried 6 April 1866; he left under £16,000: she left under £45,000 [wills index].

### Letters

- Letter from Feb 3 1900
- [To the Countess of Glasgow, Sept 25th 1898](../letters/3381_To_the_Countess_of_Glasgow.html)
- [To Frederick Orridge Macmillan, July 5th 1898](../letters/3378_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, June 28th1898](../letters/3376_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, June 23rd 1898](../letters/3375_To_Frederick_Orridge_Macmillan.html)
- Letter from Novr 30th 1897
- Letter from December 15 (1896)
- Letter from December 12, 1896
- Letter from December 8, 1896.
- Letter from Jan 26th 1895
- Letter from November 29. [1893?]
- Letter from  [August 1893]
- Letter from [dated by Coleridge after 1893]
- Letter from [1891]
- Letter from January 10 1890
- Letter from Febry 21st 1889
- Letter from July 3d [1888]
- Letter from Decr 8th [1883]
- Letter from July 4th  [1879 or later]
- Letter from October 1, 1878

*... and 91 more letters*

---

[← Back to all letters](../letters.html)
