---
title: "Frances Emily Awdry"
---

## Frances Emily Awdry

**Dates:** (30 May 1844-24 November 1921)

**Maiden name:** (Moberly)

### Description

author of elementary science textbooks

### Biography

  She was a member of the Gosling Society as ‘Humble Bee’ approximately 1859-1868. Always known as Emily, she was goddaughter to CMY\'s mother FMY.  Daughter of the Rt. Rev. George Moberly, she married (4 August 1868) the Rt. Rev. William Awdry (1842-1910). While he was a schoolmaster at Winchester, they both promoted the extension lectures.

### Letters

- [To Marianne Bigg Wither, August, 11[[footnote:1]] 1898.](../letters/3380_To_Marianne_Bigg_Wither.html)
- Letter from Aug 5th 1897
- Letter from 7 June 1892
- Letter from Oct 7th 1878
- Letter from Decr 23d [1872]
- Letter from [1872? 1873?]
- Letter from May 20th [1871?[[footnote:1]]]
- Letter from Novr 6 th [1869]
- Letter from [early] Oct. 1868.
- Letter from October 5, 1868
- Letter from Sept. 30, 1868
- Letter from [June 1864][[footnote:1]] 
- Letter from June 27th 1862
- Letter from March 24th 1862 
- Letter from Decr 30th [1861]
- Letter from Novr 19th 1861
- Letter from March 18th 1861
- Letter from June 1854.
- Letter from June 9, 1854
- Letter from [July 1853]

*... and 1 more letters*

---

[← Back to all letters](../letters.html)
