---
title: "Edith Emma Knight"
---

## Edith Emma Knight

**Dates:** (4? March 1851-1936)

**Maiden name:** (Butler)

### Description

member of the Gosling Society, daughter of the Very Rev. William John Butler

### Biography

Known as Emma Butler, she was the daughter of CMY’s great friends the Rev. William Butler, Vicar of Wantage and later Dean of Lincoln and his wife Emma Barnett (1813-1894).  A member of the Gosling Society as ‘Frog’,  she married (Oct-Dec 1877) as his third wife, Edward Lewis Knight (1817-1882), of Hornacott Manor, Cornwall.  She was an associate of the Wantage sisterhood.  She inherited her aunt Elizabeth Barnett's letters from CMY and lent them to both Coleridge and Romanes. [LG 1906 Knight of Wolverley, will, <i>Life and Letters of Dean Butler; Memoirs of Arthur John Butler</i>]

### Letters

- [To Mary Caroline Butler, April 11th 1899](../letters/3403_To_Mary_Caroline_Butler.html)
- Letter from December 12, 1896
- Letter from [December 1889]
- Letter from Aug 3d 1877 
- Letter from July 9th [before 1877[[footnote:1]]]
- Letter from Jany 6th 1875 [1876]
- Letter from Aug 7th [?1874[[footnote:1]]]
- Letter from July 1st [1871[[footnote:1]]]
- Letter from May 31 st [1870] 
- Letter from May 9th [1870] 
- Letter from Jany 28th  [1870]
- Letter from July 12th [1869]
- Letter from June 18th [1869]
- Letter from Nov 20th [1868]
- Letter from Oct 30th [1868]
- Letter from St. S[imon]. & J[ude]. [28 October] 1868
- Letter from [1861]

---

[← Back to all letters](../letters.html)
