---
title: "Ann Catherine Lloyd"
---

## Ann Catherine Lloyd

**Dates:** (Helston 1847/8-1903 Benares)

**Maiden name:** (Johns)

### Description

artist, member of the Gosling Society

### Biography

Known as Katie, she was an artist and illustrator, daughter of the Rev. [[person:769]Charles Alexander Johns].  She was a Gosling as Kittiwake in 1864-5.  She married in 1873 the Rev. John Henry Lloyd, curate of Wormleighton and subsequently Vicar of Fotheringay.  He was curate to the Rev. William Harrison, Vicar of Wormleighton, who was married to Mary Kingsley (1852-1931), daughter of Charles Kingsley and a friend of Katie Johns.  Both marriages seem to have come to grief.  In 1891 she was living apart from her husband and was matron of Annie Besant’s Women’s Home at 193 Bow Road, a kind of club for girls in the East End, with a few resident matchmakers.  A.H.Nethercot <i>The First Five Lives of Annie Besant</i> (Chicago, U of C P 1960) 337, calls her ‘Mrs Kitty Lloyd’ and describes her as ‘a devoted Theosophist’.  Later her health broke down and she was sent to Ceylon and then to Benares, where she ended her days as the much-loved Matron of the Central Hindu College Boarding House. She is mentioned in her mother’s will (1895), along with her brother Charles, as having brought her to poverty.[ [census returns 1881, 1891; marriage index;  clergy lists; Nethercot, <i>First Five Lives of Annie Besant; Theosophical Yearbook 1933</i>; Obituary in <i>The Theosophist</i>, 1903; info from Professor Joy Dixon]

### Letters

- Letter from October 10, 1890.
- Letter from April 10th  [?16th 1887]
- Letter from July 9th 1877 
- Letter from Febry 1st 1875
- Letter from July 2nd 1873
- Letter from Aug 11th [1871]
- Letter from Sept 30th [1869]
- Letter from Oct 8th [1868]
- Letter from July 1st [1868]
- Letter from September 28 [1867]
- Letter from July 9th [1867]
- Letter from Decr 22d [1865]	
- Letter from July 10. 1865
- Letter from July 4. 1865
- Letter from July 3. 1865
- Letter from July 1st 1865
- Letter from Febry 14 [1865]
- Letter from Jany 23d 1865
- Letter from Novr 22d 1864
- Letter from Oct 19th [1864]

*... and 1 more letters*

---

[← Back to all letters](../letters.html)
