---
title: "Amy Aubrey Locke"
---

## Amy Aubrey Locke

**Dates:** (1881-1916)

### Description

historian

### Biography

First holder of the Charlotte Yonge scholarship from Winchester High School, she was daughter of Alfred L. Locke, head porter to Winchester College. She is listed as a student at Somerville College Oxford in the 1901 census.  She published several works of history before her early death and was employed by the Central Office of the Victoria County History project.  She seems to have called herself Audrey in adult life.

For a description of how her substantial contribution to the Cornwall section <i>Victoria History of the Counties of England</i> remained unpublished owing to the dilatoriness of another contributor, see John Beckett, [[otherbook:1116]\'Canon Thomas Taylor of St. Just and the Victoria County History in Cornwall, 1899-1938\'] <i>Journal of the Royal Institution of Cornwall</i>  (2011) 31-44, 38-9.  Probably more material on her professional career is to be found in the Victoria County History Archive, held by the Institute of Historical Research, University of London.

### Letters

- Letter from Sept 12  [1899?]

---

[← Back to all letters](../letters.html)
