---
title: "Anne Mackenzie"
---

## Anne Mackenzie

**Dates:** (1813-11 Feb 1877)

### Description

writer on missions

### Biography

Second daughter of Colin Mackenzie (d. 1835),of Portmore,and Elizabeth (d. 1852), daughter of Sir William Forbes of Pitsligo 6th Bt., she edited <i>The Net Cast in Many Waters: Sketches from the Lives of Missionaries</i>;  and cared for her invalid nephew George Ralph Dundas (1844-1869).  [F. Awdry, <i>An Elder Sister</i>; ODNB]

### Letters

- Letter from Feb 6th [1894]
- Letter from Jan 31 [1894]   
- Letter from [1884] [[footnote:1]]
- Letter from Feb 26[or8?] 1878
- Letter from June 5th 1877 
- Letter from Oct 2nd [1876 or earlier[[footnote:1]]]
- Letter from June 17th 1876
- Letter from [August 1873][[footnote:1]]
- Letter from July 23, 1873
- Letter from Oct 11th [1869 [[footnote:2]]]
- Letter from October 8, 1869.
- Letter from August 5 [1869]
- Letter from [November 1868]
- Letter from Aug 26th [1868]
- Letter from Aug 12 [1867]
- Letter from 16 July [1867]
- Letter from June 12th [1867]
- Letter from April 12th [1867?]
- Letter from Ash Wednesday [6 March 1867?]
- Letter from January 29, 1867.

*... and 10 more letters*

---

[← Back to all letters](../letters.html)
