---
title: "Sir Frederick Orridge Macmillan"
---

## Sir Frederick Orridge Macmillan

**Dates:** (1851-1936)

### Description

nephew and partner of Alexander Macmillan

### Biography

Son of Daniel Macmillan,  he married (1874) Georgiana Elizabeth Warrin, an American;  he returned in 1876 from the U.S. to be partner in firm; he had no children; he was knighted in 1909.  [DNB]

### Letters

- Letter from Oct 5 th 1900
- Letter from Oct 2d [1900]
- [To Frederick Orridge Macmillan, March 17 1899](../letters/3400_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, March 1st 1899](../letters/3398_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, 1899](../letters/3391_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, Sept 28th 1898](../letters/3382_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, July 12th 1898](../letters/3379_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, July 5th 1898](../letters/3378_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan or Alexander Macmillan Jr, June 30th 1898](../letters/3377_To_Frederick_Orridge_Macmillan_or_Alexander_Macmillan_Jr.html)
- [To Frederick Orridge Macmillan, June 28th1898](../letters/3376_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan, June 23rd 1898](../letters/3375_To_Frederick_Orridge_Macmillan.html)
- [To Frederick Orridge Macmillan , Mar 6d [1898]](../letters/3372_To_Frederick_Orridge_Macmillan_.html)
- Letter from Decr 17th [1897]
- Letter from Decr 14th 1897
- Letter from Novr 30th 1897
- Letter from Jan 1st 1897
- Letter from Feb 28th 1896
- Letter from Febry 24th 1896
- Letter from Oct 16th 1895
- Letter from Oct 14th [1895]

*... and 5 more letters*

---

[← Back to all letters](../letters.html)
