---
title: "Mary Anne Frances Martin"
---

## Mary Anne Frances Martin

**Dates:** (1829-1922)

### Description

teacher and author

### Biography

She was head of the junior school of Bedford College from its foundation 1853 until its closure 1868, editor of the Sunday Library for Household Reading from 1867, involved in the Working Womens College, later named after her Frances Martin College, friend and flatmate of Dinah Mulock 1850-9.

### Letters

- Letter from Jany 17th 1893
- Letter from Decr 31st [1870]
- Letter from May 30th [1870] 
- Letter from Decr 17th [1869]
- Letter from August 12. [1869]
- Letter from August 11. [1869]
- Letter from August 10. [1869]
- Letter from August 9. [1869]
- Letter from August 5 [1869]
- Letter from Dec.31. 1867.
- Letter from Nov:21. 1867
- Letter from Nov: 11.1867.
- Letter from Nov: 1.1867.
- Letter from [late October] 1867
- Letter from 15th Aug. 1867.
- Letter from 10 Aug. 1867.
- Letter from  July 18th 1867
- Letter from July 18th 1867
- Letter from July 18/1867
- Letter from July 17. 1867

*... and 8 more letters*

---

[← Back to all letters](../letters.html)
