---
title: "Mary Sophia Paulina Martyn"
---

## Mary Sophia Paulina Martyn

**Dates:** (1843-1887)

### Description

member of the Gosling Society

### Biography

A Gosling as ‘Pena’, 1859-63, ‘Pena’ was her nickname in real life as well. She was the only child of the Rev. Thomas Waddon Martyn (1808-1846), Rector of Lifton and Vicar of Thorverton, and his wife Sophia (1815/6-1898), daughter of the Rev. Dr. James Coleridge (1789-1857) and his wife Sophia, daughter of Col. Stanhope Badcock. In the 1861 census she was living with this grandmother in Dawlish.  She was a cousin of CMY’s, and also of Bishop Patteson\'s, and he seems to have made a pet of her before his departure for New Zealand, mentioning her in his letters. [Vivian, <i>Visitations of Cornwall</i>;  1851 census;  PO Devon 1866;  1881 census with mother at Harleston, Cary Crescent, Torquay]

### Letters

- [To Christabel Rose Coleridge, Decr 9th  [1898]](../letters/3388_To_Christabel_Rose_Coleridge.html)
- Letter from June 25th 1885
- Letter from Ash Wednesday [6 March 1867?]
- Letter from Oct 30th [1865]
- Letter from Sept 3rd [1862][[footnote:1]]
- Letter from June 27th 1862
- Letter from Decr 31st [1861]

---

[← Back to all letters](../letters.html)
