---
title: "Blanche Catherine Medhurst"
---

## Blanche Catherine Medhurst

**Dates:** (London 1848- Barnstaple 1925)

### Description

social worker and contributor to <i>MP</i> (1873-5)

### Biography

She was daughter of Francis Hastings Medhurst (d.1852), of Kippax Hall, near Leeds, and Mary Anne Bushnan;  a friend of Mrs Mercier and patroness of Emmeline Spratt. She published a study of workhouses, <i>The Idle Room</i> (1886). [LG 1871, census] The 1861 census shows Mary Anne Medhurst with two other daughters and her mother Anne Bushman (d.1878) living at 29 Dorset Square;  in the 1871 census Blanche is there too.  Hers is an odd story, because her father killed another boy while a private pupil at school and got three years for manslaughter in 1839, coming up before Mr Justice Coleridge; his grandfather, a rich stockbroker, had murdered his wife while insane and was at that time in an asylum. [<i>Times</i>].  She wrote an article in <i>MP</i> (1886) about the Associated Workers League, of which she was evidently a member.

### Letters

- Letter from Feb 7th [1880s?]
- Letter from Sept 22d 1878[[footnote:1]]
- Letter from [1878?]
- Letter from June 5th 1877 
- Letter from March 13th 1875
- Letter from Aug 12th [1873] [[footnote:1]]
- Letter from May 9th 1873
- Letter from Decr 31st [1872]
- Letter from Decr 18th 1872

---

[← Back to all letters](../letters.html)
