---
title: "Sarah Anne Mercier"
---

## Sarah Anne Mercier

**Dates:** (Herts. 1842/3-1917)

**Maiden name:** (Northwood)

### Description

contributor to <i>MP</i> (1869-84)

### Biography

Known as Anne Mercier, she married (1868) the Rev. Jerome John Mercier, Rector of Kemerton, Glos.. A brief obituary in <i>The Times</i> (8 Feb 1917) says that ‘she helped to found the Girls’ Friendly Society as well as the Girls’ High School at Tewkesbury’ and that her son succeeded his father as Rector of Kemerton.  She was active in the GFS, and was editor at one time of <i>Friendly Leaves</i> (perhaps taking over from Christabel Coleridge in the twentieth century?).
[COPAC]

### Letters

- Letter from March 13th 1875
- Letter from Decr 18th 1872
- Letter from Oct 25th [1872]
- Letter from [1872? 1873?]
- Letter from Sept 9th [1871]
- Letter from June 8th [1870]
- Letter from June 8th [1870]
- Letter from March 5th [after 1870?]
- Letter from March 5th [1870?]
- Letter from Jan 8th [1870]
- Letter from Decr 15th [1869]
- Letter from June 22nd [1869]
- Letter from April 1st [1869]

---

[← Back to all letters](../letters.html)
