---
title: "\'Biographies of Eminent Anglicans\'"
---

## \'Biographies of Eminent Anglicans\'

**By Charlotte Mary Yonge**

**Published:** 1890s
**Genre:** Non-fiction, biography
**Format:** MS Bodleian Library, unpublished

### Notes

CMY contributed to a series of short biographies of Anglican saints at the behest of the Rev. [[person:221]J. F. W. Bullock], Rector of Radwinter.   In 1902 he finally published the first three volumes of a projected six volume work called <i>Daily Lections for every Morning and Evening throughout the Year</i> (London: Rivington 1902).  Volume V of this work, described in his preface, was to have consisted of \'Lections on Anglican Worthies, arranged as additional Readings for Sunday\'.  These \'Biographies of Eminent Anglicans\' exist in MS and are catalogued under that name among the Bullock papers in the Bodleian Library, Oxford, but were never published, since no more of the <i>Daily Lections</i> ever appeared.

---

[← Back to all letters](../../letters.html)
