---
title: "Charlotte Yonge Scholarship, The"
---

## Charlotte Yonge Scholarship, The

**Type:** topic

### About

In 1898 fund-raising began to provide a University Scholarship from Winchester High School for Girls in honour of CMY.  The appeal published in <i>MP</i> (April 1898) 469,  in <i>The Times</i> (17 March 1898) 7, and elsewhere, signed ‘Esmé Stuart’, states ‘\'The sum of £6000 will be required in order to found an Annual Scholarship of £50 to be held for three years\'.  Actually about £1800 was raised, less than had been hoped, and the first recipient, [[person:893]Amy Aubrey Locke], who was the daughter of the porter of Winchester College, was initially unable to take up the scholarship because it did not cover the entire expense. A presentation was made to CMY on 19 July 1899 in the school.  According to the report in <i>The Times</i> (22 July 1899) those present included Amelie Leroy (‘Esmé Stuart’), the Rev. J. H. Merriott, the hon. treasurer of the committee, Miss Mowbray, the Sumners, the Hon. Mrs Joyce, Mrs Harold Browne, Christabel Coleridge, Eleanor Price and Mrs Anderson Morshead. The scholarship continued to be awarded at least until the 1930s.

### Letters Mentioning This Organization

- [To Christabel Rose Coleridge, Aug 12 [1899]](../letters/3416_To_Christabel_Rose_Coleridge.html)
- [To Margaret Jane Mowbray, July 20, 1899.](../letters/3410_To_Margaret_Jane_Mowbray.html)
- [To Charlotte Fortescue Yonge, July 20, 1899](../letters/3411_To_Charlotte_Fortescue_Yonge.html)
- [To Mary Yonge, July 1st[1899]](../letters/3409_To_Mary_Yonge.html)

---

[← Back to all letters](../letters.html)
