---
title: "All Saints\' Church, Hursley"
---

## All Saints\' Church, Hursley

**Type:** place

### About

The parish church of Hursley was substantially rebuilt in 1847-8 to the designs of William Harrison, under the supervision of the Rev. John Keble, and partly funded from the profits of his bestselling volume of poetry [[otherbook:95]<i>The Christian Year</i>].  CMY describes the fittings of the interior and the symbolism of the stained glass in some detail in [[cmybook:247]<i>John Keble\'s Parishes</i>] (1898), 115-124.  She emphasises that the work coincided with the Tractarian crisis following Newman\'s secession, so that the reconstruction was an act of faith at a time of great anxiety and doubt, while the movement was the target of vilification and suspicion.  She enumerates the gifts made by Keble\'s friends and supporters to beautify the building, and no doubt they symbolize among other things the dependence placed on him at that time.

---

[← Back to all letters](../letters.html)
