---
title: "<i>Monthly Packet, The</i>"
---

## <i>Monthly Packet, The</i>

**Type:** periodical

### About

This monthly magazine was edited by CMY 1851-1890; edited by CMY jointly with C. R. Coleridge 1891-3; edited by C. R. Coleridge and A. D. Innes 1894-9. It was markedly High Church and aimed at a juvenile audience, mainly conceived of as girls in their teens, though in the early days CMY also hoped to make it entertaining to boys who had not yet gone to public school, and there is evidence that it was also read by adults of both sexes.   The magazine has been digitized in the series <i>19th Century UK Periodicals</i> and is available at http://find.galegroup.com/ukpc/

### Letters Mentioning This Organization

- [To Christabel Rose Coleridge,  [15 August 1899]   ](../letters/3418_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge, Aug 12 [1899]](../letters/3416_To_Christabel_Rose_Coleridge.html)
- [To Christabel Rose Coleridge, July 23d [1899]](../letters/3412_To_Christabel_Rose_Coleridge.html)
- [To Charlotte Fortescue Yonge, July 20, 1899](../letters/3411_To_Charlotte_Fortescue_Yonge.html)
- [To Mary Yonge, July 1st[1899]](../letters/3409_To_Mary_Yonge.html)
- [To Lady Leconfield, May 26th [1899]](../letters/3407_To_Lady_Leconfield.html)
- [To Sir Walter Besant, Febry 7th [1899?][[footnote:1]]](../letters/3394_To_Sir_Walter_Besant.html)

*... and 193 more*

---

[← Back to all letters](../letters.html)
